/*
===============================================================================
 PostgreSQL Trigger 완전정리 및 종합 실습
===============================================================================

 [학습 목표]
  1. PostgreSQL 트리거와 트리거 함수의 관계를 이해한다.
  2. BEFORE / AFTER / INSTEAD OF의 차이를 이해한다.
  3. INSERT / UPDATE / DELETE / TRUNCATE 사건을 구분한다.
  4. FOR EACH ROW / FOR EACH STATEMENT의 차이를 이해한다.
  5. NEW / OLD / TG_OP 등 트리거 특수 변수를 사용한다.
  6. 감사 로그, 수정 시각, 상태 이력을 자동으로 관리한다.
  7. 벌크 INSERT에서 행 단위 트리거가 미치는 영향을 확인한다.
  8. 전환 테이블을 이용하여 변경된 여러 행을 집합으로 처리한다.
  9. 트리거 조회, 비활성화, 활성화, 삭제 방법을 익힌다.
 10. 트리거가 적합한 경우와 제약조건이 적합한 경우를 구분한다.

 [중요]
  - 이 파일은 실습 전용 trigger_lab 스키마를 삭제한 후 다시 생성한다.
  - trigger_lab 스키마에 보관할 데이터가 있다면 먼저 백업한다.
  - DBeaver에서 전체 실행하거나 구역별로 선택하여 실행할 수 있다.

 [공식 문서]
  - https://www.postgresql.org/docs/current/sql-createtrigger.html
  - https://www.postgresql.org/docs/current/plpgsql-trigger.html
  - https://www.postgresql.org/docs/current/trigger-definition.html
  - https://www.postgresql.org/docs/current/sql-copy.html

===============================================================================
 0. 핵심 개념
===============================================================================

 트리거(trigger)는 테이블이나 뷰에서 특정 사건이 발생했을 때
 PostgreSQL이 지정된 함수를 자동으로 실행하게 하는 데이터베이스 객체다.

   INSERT / UPDATE / DELETE / TRUNCATE 발생
                        ↓
                  트리거가 감지
                        ↓
                  트리거 함수 실행

 PostgreSQL 트리거는 다음 두 객체로 구성된다.

   1) 트리거 함수
      - 실제로 수행할 작업을 작성한다.
      - 일반적으로 PL/pgSQL로 작성한다.
      - 일반 매개변수를 선언하지 않는다.
      - 반드시 RETURNS trigger로 선언한다.

   2) 트리거
      - 언제 실행할지 지정한다.
      - 어떤 사건에서 실행할지 지정한다.
      - 행마다 실행할지, 문장마다 실행할지 지정한다.
      - 실행할 트리거 함수를 연결한다.

 트리거를 이해하는 세 가지 기준

   실행 시점 : BEFORE / AFTER / INSTEAD OF
   실행 사건 : INSERT / UPDATE / DELETE / TRUNCATE
   실행 단위 : ROW / STATEMENT

 PostgreSQL은 MySQL처럼 CREATE TRIGGER 문 안에 처리 SQL을 직접 작성하지 않는다.
 트리거 정의는 실행할 트리거 함수를 참조해야 한다.

 CREATE TRIGGER 문에서 과거 문법인 EXECUTE PROCEDURE를 허용하는 버전도 있지만
 실제 대상은 프로시저가 아니라 함수다. 현재는 EXECUTE FUNCTION을 사용한다.

 트리거와 트리거가 호출한 함수는 원본 SQL과 같은 트랜잭션에 참여한다.
 따라서 트리거에서 오류가 발생하면 원본 INSERT, UPDATE, DELETE도 롤백된다.
*/


/*
===============================================================================
 1. 실습 환경 초기화
===============================================================================
*/

DROP SCHEMA IF EXISTS trigger_lab CASCADE;

CREATE SCHEMA trigger_lab;

COMMENT ON SCHEMA trigger_lab IS
    'PostgreSQL 트리거 완전정리 및 종합 실습용 스키마';

SET search_path TO trigger_lab, public;


/*
===============================================================================
 2. 실습 테이블 생성
===============================================================================

 orders
   - 트리거가 부착될 원본 주문 테이블

 order_audit
   - INSERT / UPDATE / DELETE 전후 데이터를 JSONB로 기록

 order_status_history
   - 주문 상태가 실제로 변경된 경우에만 기록

 order_batch_log
   - 한 INSERT 문장에서 입력된 전체 행 수 기록

 table_event_log
   - TG_ARGV와 TRUNCATE 문장 단위 트리거 실습
*/

CREATE TABLE orders (
    order_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    bigint NOT NULL,
    order_status   varchar(20) NOT NULL DEFAULT 'PENDING',
    total_amount   numeric(12, 2) NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at     timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT chk_orders_total_amount
        CHECK (total_amount >= 0),

    CONSTRAINT chk_orders_status
        CHECK (
            order_status IN (
                'PENDING',
                'PAID',
                'SHIPPING',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

COMMENT ON TABLE orders IS
    '트리거 실습용 주문 테이블';

COMMENT ON COLUMN orders.updated_at IS
    'BEFORE UPDATE 트리거가 자동으로 변경하는 최종 수정 시각';


CREATE TABLE order_audit (
    audit_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       bigint,
    operation      varchar(10) NOT NULL,
    old_data       jsonb,
    new_data       jsonb,
    trigger_name   text NOT NULL,
    changed_by     text NOT NULL,
    changed_at     timestamptz NOT NULL
);

COMMENT ON TABLE order_audit IS
    '주문 INSERT, UPDATE, DELETE 감사 로그';


CREATE TABLE order_status_history (
    history_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       bigint NOT NULL,
    old_status     varchar(20),
    new_status     varchar(20) NOT NULL,
    changed_by     text NOT NULL,
    changed_at     timestamptz NOT NULL
);

COMMENT ON TABLE order_status_history IS
    '주문 상태가 실제 변경된 경우만 기록하는 이력 테이블';


CREATE TABLE order_batch_log (
    batch_log_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name     text NOT NULL,
    inserted_count bigint NOT NULL,
    logged_at      timestamptz NOT NULL
);

COMMENT ON TABLE order_batch_log IS
    '문장 단위 트리거와 전환 테이블을 이용한 벌크 INSERT 요약 로그';


CREATE TABLE table_event_log (
    event_log_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_label    text NOT NULL,
    schema_name    text NOT NULL,
    table_name     text NOT NULL,
    operation      text NOT NULL,
    trigger_level  text NOT NULL,
    occurred_at    timestamptz NOT NULL
);

COMMENT ON TABLE table_event_log IS
    'TG_ARGV와 TG_ 계열 특수 변수 실습용 테이블';


/*
===============================================================================
 3. BEFORE 트리거 ① 입력값 정규화
===============================================================================

 BEFORE 트리거
   - 실제 데이터가 저장되기 전에 실행된다.
   - NEW 값을 직접 수정할 수 있다.
   - 수정한 NEW를 RETURN NEW로 반환하면 변경된 값이 저장된다.
   - RETURN NULL을 반환하면 해당 행의 작업을 건너뛴다.

 이 예제는 주문 상태에 공백이 있거나 소문자로 입력되어도
 공백을 제거하고 대문자로 변환한다.

 예:
   ' paid ' → 'PAID'
*/

CREATE OR REPLACE FUNCTION fn_normalize_order_status()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.order_status := upper(trim(NEW.order_status));

    RETURN NEW;
END;
$function$;


CREATE TRIGGER trg_10_orders_normalize_status
BEFORE INSERT OR UPDATE OF order_status
ON orders
FOR EACH ROW
EXECUTE FUNCTION fn_normalize_order_status();


/*
 입력값 정규화 확인

 BEFORE 트리거가 먼저 ' paid '를 'PAID'로 변경한 후,
 CHECK 제약조건이 최종 값을 검사한다.
*/

INSERT INTO orders (
    customer_id,
    order_status,
    total_amount
)
VALUES (
    101,
    ' paid ',
    50000
)
RETURNING
    order_id,
    customer_id,
    order_status,
    total_amount,
    created_at,
    updated_at;


/*
===============================================================================
 4. BEFORE 트리거 ② updated_at 자동 변경
===============================================================================

 UPDATE 문에서 매번 다음 코드를 직접 작성할 수도 있다.

   UPDATE orders
   SET order_status = 'SHIPPING',
       updated_at = clock_timestamp()
   WHERE order_id = 1;

 하지만 개발자가 updated_at 갱신을 빠뜨릴 수 있다.
 트리거로 구현하면 어떤 프로그램이나 사용자가 UPDATE해도
 데이터베이스가 updated_at을 일관되게 변경한다.

 updated_at은 AFTER가 아니라 BEFORE UPDATE에서 변경하는 것이 적합하다.

   BEFORE UPDATE
     - 아직 저장되기 전의 NEW.updated_at을 변경
     - 변경된 NEW가 한 번의 UPDATE로 최종 저장됨

   AFTER UPDATE
     - 이미 저장이 끝난 다음 실행
     - NEW를 변경해도 원본 행에 반영되지 않음
     - 다시 UPDATE해야 하므로 트리거 재실행과 재귀 위험 발생
*/

CREATE OR REPLACE FUNCTION fn_set_orders_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at := clock_timestamp();

    RETURN NEW;
END;
$function$;


CREATE TRIGGER trg_20_orders_set_updated_at
BEFORE UPDATE
ON orders
FOR EACH ROW
EXECUTE FUNCTION fn_set_orders_updated_at();


/*
 updated_at 자동 변경 확인
*/

UPDATE orders
SET order_status = ' shipping '
WHERE order_id = 1
RETURNING
    order_id,
    order_status,
    updated_at;


/*
===============================================================================
 5. AFTER 트리거: INSERT / UPDATE / DELETE 감사 로그
===============================================================================

 AFTER 트리거
   - 원본 행의 작업이 완료된 후 실행된다.
   - 감사 로그, 이력 저장, 후속 업무 처리에 적합하다.
   - AFTER 행 트리거의 반환값은 원본 행에 영향을 주지 않는다.
   - 따라서 일반적으로 RETURN NULL을 사용한다.

 NEW / OLD 사용 가능 여부

   작업       OLD                   NEW
   ----------------------------------------------------
   INSERT     사용할 수 없음        입력된 행
   UPDATE     변경 전 행            변경 후 행
   DELETE     삭제될 행             사용할 수 없음

 문장 단위 트리거와 TRUNCATE 트리거에서는 NEW / OLD를 사용하지 않는다.
*/

CREATE OR REPLACE FUNCTION fn_audit_orders()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    v_order_id bigint;
    v_old_data jsonb;
    v_new_data jsonb;
BEGIN
    /*
     TG_OP
       - 현재 트리거를 발생시킨 작업명
       - INSERT / UPDATE / DELETE / TRUNCATE
    */
    CASE TG_OP
        WHEN 'INSERT' THEN
            v_order_id := NEW.order_id;
            v_new_data := to_jsonb(NEW);

        WHEN 'UPDATE' THEN
            v_order_id := NEW.order_id;
            v_old_data := to_jsonb(OLD);
            v_new_data := to_jsonb(NEW);

        WHEN 'DELETE' THEN
            v_order_id := OLD.order_id;
            v_old_data := to_jsonb(OLD);

        ELSE
            RAISE EXCEPTION '지원하지 않는 트리거 작업입니다: %', TG_OP;
    END CASE;

    INSERT INTO trigger_lab.order_audit (
        order_id,
        operation,
        old_data,
        new_data,
        trigger_name,
        changed_by,
        changed_at
    )
    VALUES (
        v_order_id,
        TG_OP,
        v_old_data,
        v_new_data,
        TG_NAME,
        session_user,
        clock_timestamp()
    );

    /*
     AFTER 트리거에서는 반환값이 무시된다.
    */
    RETURN NULL;
END;
$function$;


CREATE TRIGGER trg_90_orders_audit
AFTER INSERT OR UPDATE OR DELETE
ON orders
FOR EACH ROW
EXECUTE FUNCTION fn_audit_orders();


/*
 감사 트리거 작동 확인

 주의:
   감사 트리거를 생성하기 전에 실행했던 주문 1번의 INSERT와 UPDATE는
   감사 테이블에 기록되지 않는다.
   트리거는 생성된 이후의 사건부터 감지한다.
*/

INSERT INTO orders (
    customer_id,
    order_status,
    total_amount
)
VALUES (
    102,
    'pending',
    75000
)
RETURNING order_id;


UPDATE orders
SET
    order_status = 'PAID',
    total_amount = 80000
WHERE order_id = 2;


DELETE FROM orders
WHERE order_id = 2;


SELECT
    audit_id,
    order_id,
    operation,
    old_data,
    new_data,
    trigger_name,
    changed_by,
    changed_at
FROM order_audit
ORDER BY audit_id;


/*
===============================================================================
 6. UPDATE OF + WHEN: 실제 상태 변경만 기록
===============================================================================

 UPDATE OF order_status
   - UPDATE 문의 SET 절에 order_status가 포함되면 대상이 된다.
   - 실제 값이 바뀌었는지까지 판단하지는 않는다.

 예:
   UPDATE orders
   SET order_status = order_status
   WHERE order_id = 1;

 위 SQL은 SET 절에 order_status가 있으므로 UPDATE OF 조건에는 해당한다.
 그러나 실제 상태값은 변경되지 않았다.

 WHEN (OLD.order_status IS DISTINCT FROM NEW.order_status)
   - 변경 전후 값이 실제로 다를 때만 트리거 함수를 호출한다.
   - IS DISTINCT FROM은 NULL 비교도 안전하게 처리한다.

 일반 감사 로그는 order_audit에 기록하고,
 상태 변경 전용 기록은 order_status_history에 저장한다.
 따라서 두 트리거의 목적과 저장 대상이 서로 다르다.
*/

CREATE OR REPLACE FUNCTION fn_log_order_status_change()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO order_status_history (
        order_id,
        old_status,
        new_status,
        changed_by,
        changed_at
    )
    VALUES (
        NEW.order_id,
        OLD.order_status,
        NEW.order_status,
        session_user,
        clock_timestamp()
    );

    RETURN NULL;
END;
$function$;


CREATE TRIGGER trg_30_orders_status_history
AFTER UPDATE OF order_status
ON orders
FOR EACH ROW
WHEN (
    OLD.order_status IS DISTINCT FROM NEW.order_status
)
EXECUTE FUNCTION fn_log_order_status_change();


/*
 실제 값이 같으므로 상태 이력 트리거는 실행되지 않는다.
 일반 감사 트리거는 모든 UPDATE를 기록하므로 order_audit에는 기록된다.
*/

UPDATE orders
SET order_status = order_status
WHERE order_id = 1;


/*
 실제 상태가 변경되므로 상태 이력과 일반 감사 로그에 모두 기록된다.
*/

UPDATE orders
SET order_status = 'COMPLETED'
WHERE order_id = 1;


SELECT
    history_id,
    order_id,
    old_status,
    new_status,
    changed_by,
    changed_at
FROM order_status_history
ORDER BY history_id;


/*
===============================================================================
 7. 행 단위 트리거와 문장 단위 트리거
===============================================================================

 ① FOR EACH ROW

   영향받은 행마다 트리거 함수가 실행된다.

   INSERT 1,000행
      → 행 단위 트리거 함수 1,000번 실행

   개별 행의 NEW / OLD가 필요할 때 사용한다.
   감사 로그, 개별 데이터 보정 등에 적합하다.

 ② FOR EACH STATEMENT

   SQL 문장 한 번당 트리거 함수가 한 번 실행된다.

   INSERT 1,000행
      → 문장 단위 트리거 함수 1번 실행

   영향을 받은 행이 0건이어도 해당 SQL 문장이 실행되면
   문장 단위 트리거는 실행될 수 있다.

 CREATE TRIGGER에서 FOR EACH ROW와 FOR EACH STATEMENT를 모두 생략하면
 기본값은 FOR EACH STATEMENT다.
*/


/*
===============================================================================
 8. 전환 테이블: 벌크 INSERT 결과를 집합으로 처리
===============================================================================

 문장 단위 트리거에는 한 행을 의미하는 NEW / OLD가 없다.

 대신 AFTER 트리거에서 전환 테이블(transition table)을 사용하면
 한 SQL 문장으로 변경된 전체 행을 집합으로 참조할 수 있다.

   REFERENCING NEW TABLE AS inserted_rows

 inserted_rows
   - 현재 INSERT 문장으로 입력된 전체 행을 담은 임시 관계
   - 트리거 함수에서 일반 테이블처럼 SELECT할 수 있음

 이 방식은 개별 행을 반복 처리하지 않고 집합 기반으로 처리할 때 유용하다.
*/

CREATE OR REPLACE FUNCTION fn_log_order_insert_batch()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    v_inserted_count bigint;
BEGIN
    SELECT count(*)
    INTO v_inserted_count
    FROM inserted_rows;

    INSERT INTO order_batch_log (
        table_name,
        inserted_count,
        logged_at
    )
    VALUES (
        TG_TABLE_NAME,
        v_inserted_count,
        clock_timestamp()
    );

    RETURN NULL;
END;
$function$;


CREATE TRIGGER trg_80_orders_insert_batch
AFTER INSERT
ON orders
REFERENCING NEW TABLE AS inserted_rows
FOR EACH STATEMENT
EXECUTE FUNCTION fn_log_order_insert_batch();


/*
 벌크 INSERT 실습

 하나의 INSERT 문장으로 주문 1,000건을 입력한다.

 실행 예상:
   - trg_10_orders_normalize_status : 1,000번
   - trg_90_orders_audit            : 1,000번
   - trg_80_orders_insert_batch      : 1번

 즉, SQL 문장은 한 번 실행했지만 행 단위 트리거는 행 수만큼 실행된다.
*/

INSERT INTO orders (
    customer_id,
    order_status,
    total_amount
)
SELECT
    1000 + g,
    CASE
        WHEN g % 3 = 0 THEN 'paid'
        ELSE 'pending'
    END,
    10000 + (g % 10) * 1000
FROM generate_series(1, 1000) AS s(g);


/*
 문장 단위 트리거는 한 번 실행되었고 inserted_count는 1,000이다.
*/

SELECT
    batch_log_id,
    table_name,
    inserted_count,
    logged_at
FROM order_batch_log
ORDER BY batch_log_id;


/*
 행 단위 감사 트리거는 1,000개의 INSERT 로그를 추가했다.
*/

SELECT
    operation,
    count(*) AS audit_count
FROM order_audit
GROUP BY operation
ORDER BY operation;


/*
===============================================================================
 9. 벌크 INSERT란 무엇인가?
===============================================================================

 벌크 INSERT(Bulk Insert)는 많은 데이터를 한꺼번에 입력하는 방식이다.

 ① 여러 VALUES를 한 INSERT 문장으로 입력

   INSERT INTO orders(customer_id, total_amount)
   VALUES
       (2001, 10000),
       (2002, 20000),
       (2003, 30000);

 ② SELECT 결과를 한꺼번에 입력

   INSERT INTO orders(customer_id, total_amount)
   SELECT customer_id, 10000
   FROM customers;

 ③ COPY를 이용하여 CSV 등의 데이터를 고속 적재

   COPY orders(customer_id, order_status, total_amount)
   FROM '/data/orders.csv'
   WITH (
       FORMAT csv,
       HEADER true,
       ENCODING 'UTF8'
   );

 COPY FROM도 대상 테이블의 트리거와 제약조건을 실행한다.
 따라서 COPY를 사용한다고 해서 행 단위 트리거 비용이 사라지는 것은 아니다.

 벌크 INSERT와 행 단위 트리거에서 발생할 수 있는 문제

   - 트리거 함수가 행 수만큼 반복 실행됨
   - 원본 테이블과 감사 테이블의 WAL 증가
   - 트랜잭션과 잠금 유지 시간 증가
   - 트리거가 다른 테이블을 수정하면 연쇄 작업 증가
   - 마지막 행에서 오류가 발생해도 전체 문장이 롤백될 수 있음
   - 같은 테이블을 다시 수정하면 재귀 호출 위험

 대응 방법

   - WHEN 조건으로 불필요한 실행을 줄인다.
   - 트리거 함수 안에서 행마다 무거운 SELECT를 반복하지 않는다.
   - 가능하면 전환 테이블과 집합 기반 SQL을 사용한다.
   - 대량 데이터를 적절한 배치 크기로 나눈다.
   - 대량 적재 후 별도 집합 SQL로 후처리하는 방법도 검토한다.
   - 트리거를 비활성화하기 전 무결성 및 감사 누락 위험을 검토한다.
*/


/*
===============================================================================
 10. TG_ 특수 변수와 TG_ARGV
===============================================================================

 트리거 함수에서 사용할 수 있는 주요 특수 변수

   TG_NAME
     - 실행된 트리거 이름

   TG_OP
     - INSERT / UPDATE / DELETE / TRUNCATE

   TG_WHEN
     - BEFORE / AFTER / INSTEAD OF

   TG_LEVEL
     - ROW / STATEMENT

   TG_TABLE_NAME
     - 트리거 대상 테이블명

   TG_TABLE_SCHEMA
     - 트리거 대상 스키마명

   TG_NARGS
     - CREATE TRIGGER에서 전달한 인수 개수

   TG_ARGV
     - CREATE TRIGGER에서 전달한 문자열 인수 배열
     - 배열 인덱스는 0부터 시작

 트리거 함수는 일반 매개변수를 선언하면 안 된다.

   잘못된 예:
     CREATE FUNCTION fn_trigger(p_label text)
     RETURNS trigger ...

 트리거에 필요한 인수는 CREATE TRIGGER 끝에서 전달하고
 함수에서는 TG_ARGV[0], TG_ARGV[1]처럼 사용한다.
*/

CREATE OR REPLACE FUNCTION fn_log_table_event()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    v_event_label text;
BEGIN
    v_event_label := COALESCE(TG_ARGV[0], 'NO_LABEL');

    INSERT INTO table_event_log (
        event_label,
        schema_name,
        table_name,
        operation,
        trigger_level,
        occurred_at
    )
    VALUES (
        v_event_label,
        TG_TABLE_SCHEMA,
        TG_TABLE_NAME,
        TG_OP,
        TG_LEVEL,
        clock_timestamp()
    );

    RETURN NULL;
END;
$function$;


CREATE TRIGGER trg_orders_truncate_event
AFTER TRUNCATE
ON orders
FOR EACH STATEMENT
EXECUTE FUNCTION fn_log_table_event('ORDER_TABLE_TRUNCATED');


/*
 TRUNCATE 트리거 테스트

 TRUNCATE는 모든 행을 제거하므로 안전하게 트랜잭션 안에서 실행한 뒤
 결과를 확인하고 ROLLBACK한다.

 ROLLBACK하면 orders의 TRUNCATE와 table_event_log 입력이 모두 취소된다.
 이는 트리거가 원본 SQL과 같은 트랜잭션에 참여한다는 것을 보여준다.
*/

BEGIN;

TRUNCATE TABLE orders;

SELECT
    event_log_id,
    event_label,
    schema_name,
    table_name,
    operation,
    trigger_level,
    occurred_at
FROM table_event_log
ORDER BY event_log_id;

ROLLBACK;


/*
 ROLLBACK 후에는 주문 데이터가 다시 보이고,
 방금 트리거가 입력했던 TRUNCATE 로그는 남지 않는다.
*/

SELECT count(*) AS orders_after_rollback
FROM orders;

SELECT count(*) AS event_logs_after_rollback
FROM table_event_log;


/*
===============================================================================
 11. INSTEAD OF 트리거: 뷰의 INSERT 대신 처리
===============================================================================

 INSTEAD OF 트리거
   - 원래 작업을 실행하지 않고 트리거 함수가 대신 처리한다.
   - 주로 뷰의 INSERT / UPDATE / DELETE 동작을 정의할 때 사용한다.
   - 행 단위 트리거로 작성한다.

 아래 뷰는 PENDING 주문만 보여준다.
 뷰에 INSERT하면 INSTEAD OF 트리거가 실제 orders 테이블에 입력한다.
*/

CREATE VIEW v_pending_orders AS
SELECT
    order_id,
    customer_id,
    order_status,
    total_amount,
    created_at,
    updated_at
FROM orders
WHERE order_status = 'PENDING';


CREATE OR REPLACE FUNCTION fn_insert_pending_order_view()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    /*
     뷰 INSERT에서 order_status를 생략하면 PENDING으로 설정한다.
    */
    NEW.order_status := COALESCE(
        upper(trim(NEW.order_status)),
        'PENDING'
    );

    IF NEW.order_status <> 'PENDING' THEN
        RAISE EXCEPTION
            'v_pending_orders에는 PENDING 주문만 입력할 수 있습니다.'
            USING ERRCODE = '23514';
    END IF;

    INSERT INTO orders (
        customer_id,
        order_status,
        total_amount
    )
    VALUES (
        NEW.customer_id,
        NEW.order_status,
        NEW.total_amount
    )
    RETURNING
        order_id,
        customer_id,
        order_status,
        total_amount,
        created_at,
        updated_at
    INTO
        NEW.order_id,
        NEW.customer_id,
        NEW.order_status,
        NEW.total_amount,
        NEW.created_at,
        NEW.updated_at;

    /*
     INSTEAD OF 트리거에서 NULL이 아닌 행을 반환하면
     트리거가 해당 행을 처리했음을 PostgreSQL에 알린다.
    */
    RETURN NEW;
END;
$function$;


CREATE TRIGGER trg_v_pending_orders_insert
INSTEAD OF INSERT
ON v_pending_orders
FOR EACH ROW
EXECUTE FUNCTION fn_insert_pending_order_view();


/*
 뷰에 입력하지만 실제 데이터는 orders에 저장된다.
 orders에 부착된 INSERT 트리거들도 실행된다.
*/

INSERT INTO v_pending_orders (
    customer_id,
    total_amount
)
VALUES (
    3001,
    45000
)
RETURNING
    order_id,
    customer_id,
    order_status,
    total_amount;


SELECT
    order_id,
    customer_id,
    order_status,
    total_amount
FROM orders
WHERE customer_id = 3001;


/*
===============================================================================
 12. RETURN NEW / RETURN OLD / RETURN NULL 정리
===============================================================================

   트리거 종류              일반 반환값        의미
   -------------------------------------------------------------------
   BEFORE INSERT            RETURN NEW         입력 계속
   BEFORE UPDATE            RETURN NEW         변경 계속
   BEFORE DELETE            RETURN OLD         삭제 계속
   BEFORE 행 트리거         RETURN NULL        해당 행 작업 건너뜀
   AFTER 트리거             RETURN NULL        반환값이 원본 행에 영향 없음
   INSTEAD OF INSERT/UPDATE RETURN NEW         대신 처리했음을 알림
   INSTEAD OF DELETE        RETURN OLD         대신 처리했음을 알림

 다음처럼 RETURN NULL을 이용해 특정 행을 조용히 건너뛸 수도 있다.

   IF NEW.total_amount < 0 THEN
       RETURN NULL;
   END IF;

 그러나 잘못된 데이터가 사라진 이유를 사용자가 알기 어렵다.
 업무상 오류라면 RAISE EXCEPTION으로 명확히 알리는 것이 일반적으로 낫다.

   IF NEW.total_amount < 0 THEN
       RAISE EXCEPTION '주문금액은 음수가 될 수 없습니다.'
           USING ERRCODE = '23514';
   END IF;

 더 단순한 규칙이라면 트리거 대신 CHECK 제약조건을 우선 사용한다.
 현재 orders.total_amount에는 이미 다음 제약조건이 있다.

   CHECK (total_amount >= 0)
*/


/*
===============================================================================
 13. 트리거 실행 순서
===============================================================================

 일반적인 UPDATE 트리거 실행 흐름

   BEFORE STATEMENT
          ↓
   BEFORE ROW
          ↓
   실제 행 변경
          ↓
   AFTER ROW
          ↓
   AFTER STATEMENT

 여러 행이 변경되면 행 단위 단계가 각 행에 적용된다.

 동일한 테이블에 같은 종류의 트리거가 여러 개 있으면
 트리거 이름의 알파벳순으로 실행된다.

 이 파일에서는 의도를 쉽게 확인하도록 다음처럼 번호를 사용했다.

   trg_10_orders_normalize_status
   trg_20_orders_set_updated_at
   trg_30_orders_status_history
   trg_80_orders_insert_batch
   trg_90_orders_audit

 단, 트리거 사이에 지나치게 복잡한 실행 순서 의존성이 생긴다면
 관련 작업을 하나의 함수로 통합하는 방안을 검토한다.
*/


/*
===============================================================================
 14. 트리거 재귀 호출 주의
===============================================================================

 잘못된 예:

   CREATE FUNCTION fn_bad_updated_at()
   RETURNS trigger
   LANGUAGE plpgsql
   AS $$
   BEGIN
       UPDATE orders
       SET updated_at = clock_timestamp()
       WHERE order_id = NEW.order_id;

       RETURN NEW;
   END;
   $$;

 위 함수를 orders의 AFTER UPDATE 트리거에 연결하면 다음 일이 발생할 수 있다.

   orders UPDATE
       → AFTER UPDATE 트리거
       → 함수 내부에서 orders UPDATE
       → AFTER UPDATE 트리거 재실행
       → 반복

 updated_at처럼 현재 행의 값을 변경할 때는
 BEFORE UPDATE에서 NEW를 직접 변경하는 것이 안전하다.

   NEW.updated_at := clock_timestamp();
   RETURN NEW;

 트리거 함수 안에서 현재 중첩 깊이를 확인할 수는 있다.

   SELECT pg_trigger_depth();

 그러나 깊이 검사로 억지로 막기보다 재귀가 발생하지 않는 구조가 우선이다.
*/


/*
===============================================================================
 15. 트리거와 트랜잭션
===============================================================================

 트리거는 원본 SQL과 같은 트랜잭션에서 실행된다.

 원본 SQL 성공
   → 트리거 함수 실행
   → 트리거 함수에서 오류 발생
   → 원본 SQL과 트리거 작업 모두 롤백

 아래 실습에서는 주문과 감사 로그가 트랜잭션 안에서는 보이지만
 ROLLBACK 후에는 둘 다 사라진다.
*/

BEGIN;

INSERT INTO orders (
    customer_id,
    order_status,
    total_amount
)
VALUES (
    9999,
    'PENDING',
    99000
);

SELECT count(*) AS order_count_in_transaction
FROM orders
WHERE customer_id = 9999;

SELECT count(*) AS audit_count_in_transaction
FROM order_audit
WHERE new_data ->> 'customer_id' = '9999';

ROLLBACK;


SELECT count(*) AS order_count_after_rollback
FROM orders
WHERE customer_id = 9999;

SELECT count(*) AS audit_count_after_rollback
FROM order_audit
WHERE new_data ->> 'customer_id' = '9999';


/*
 감사 트리거의 중요한 한계

 원본 트랜잭션이 ROLLBACK되면 트리거가 기록한 감사 로그도 함께 사라진다.
 따라서 성공한 데이터 변경 이력에는 적합하지만,
 실패한 시도까지 반드시 남겨야 하는 보안 감사에서는
 일반 트리거 외에 데이터베이스 로그, 외부 감사 시스템 등을 검토해야 한다.
*/


/*
===============================================================================
 16. 트리거 성능 측정
===============================================================================

 EXPLAIN ANALYZE는 SQL을 실제로 실행한다.
 INSERT / UPDATE / DELETE 성능을 측정할 때 데이터 변경을 남기지 않으려면
 BEGIN과 ROLLBACK으로 감싼다.

 실행계획에서 Trigger 항목의 time과 calls를 확인할 수 있다.

 예:
   Trigger trg_30_orders_status_history: time=... calls=...
   Trigger trg_90_orders_audit:          time=... calls=...

 Execution Time에는 실행된 트리거의 시간도 포함된다.
*/

BEGIN;

EXPLAIN (ANALYZE, BUFFERS)
UPDATE orders
SET order_status = 'PAID'
WHERE order_status = 'PENDING';

ROLLBACK;


/*
===============================================================================
 17. 등록된 트리거 조회
===============================================================================

 pg_trigger
   - PostgreSQL 트리거 정보를 보관하는 시스템 카탈로그

 tgisinternal = false
   - PostgreSQL이 제약조건 등을 위해 내부적으로 생성한 트리거를 제외
   - 사용자가 직접 생성한 트리거만 조회
*/

SELECT
    ns.nspname AS schema_name,
    cls.relname AS table_name,
    trg.tgname AS trigger_name,
    trg.tgenabled AS enabled_status,
    pg_get_triggerdef(trg.oid) AS trigger_definition
FROM pg_trigger AS trg
JOIN pg_class AS cls
    ON cls.oid = trg.tgrelid
JOIN pg_namespace AS ns
    ON ns.oid = cls.relnamespace
WHERE trg.tgisinternal = false
  AND ns.nspname = 'trigger_lab'
ORDER BY
    ns.nspname,
    cls.relname,
    trg.tgname;


/*
 psql에서는 다음 명령으로 테이블의 트리거를 확인할 수 있다.

   \d trigger_lab.orders

 주의:
   \d는 psql 전용 메타 명령이다.
   DBeaver SQL 편집기에서는 위 pg_trigger 조회 SQL을 사용한다.
*/


/*
===============================================================================
 18. 트리거 비활성화와 활성화
===============================================================================

 특정 트리거 비활성화

   ALTER TABLE trigger_lab.orders
   DISABLE TRIGGER trg_90_orders_audit;

 특정 트리거 활성화

   ALTER TABLE trigger_lab.orders
   ENABLE TRIGGER trg_90_orders_audit;

 사용자 정의 트리거 전체 비활성화

   ALTER TABLE trigger_lab.orders
   DISABLE TRIGGER USER;

 사용자 정의 트리거 전체 활성화

   ALTER TABLE trigger_lab.orders
   ENABLE TRIGGER USER;

 DISABLE TRIGGER ALL은 외래키 같은 내부 제약조건 트리거에도 영향을 줄 수 있다.
 내부 제약조건 트리거의 비활성화에는 높은 권한이 필요하며,
 실행되지 않으면 참조 무결성을 보장할 수 없다.

 대량 입력을 빠르게 하겠다는 이유만으로 트리거를 비활성화하면
 다음 문제가 발생할 수 있다.

   - 감사 로그 누락
   - updated_at 미갱신
   - 상태 이력 누락
   - 업무 규칙 미적용
   - 외래키 무결성 훼손

 따라서 비활성화 전에 트리거의 업무 목적과 후처리 계획을 확인해야 한다.
*/


/*
===============================================================================
 19. 트리거 삭제
===============================================================================

 트리거는 특정 테이블에 소속되므로 삭제할 때 테이블명을 함께 작성한다.

   DROP TRIGGER IF EXISTS trg_90_orders_audit
   ON trigger_lab.orders;

 트리거를 삭제해도 트리거 함수는 자동으로 삭제되지 않는다.

   DROP FUNCTION IF EXISTS trigger_lab.fn_audit_orders();

 함수 하나를 여러 트리거가 함께 사용할 수 있으므로,
 함수 삭제 전에 의존하는 트리거가 남아 있는지 확인해야 한다.

 이 실습에서는 이후 조회를 위해 실제 삭제 명령을 실행하지 않는다.
*/


/*
===============================================================================
 20. SECURITY DEFINER 사용 시 주의
===============================================================================

 기본 함수는 SECURITY INVOKER다.
 즉, 함수를 실행한 사용자의 권한으로 내부 SQL을 실행한다.

 감사 테이블에 직접 INSERT 권한이 없는 사용자도
 트리거를 통해 감사 로그를 남겨야 하는 경우
 SECURITY DEFINER를 검토할 수 있다.

 SECURITY DEFINER
   - 함수 소유자의 권한으로 실행
   - 권한 상승이 발생할 수 있으므로 안전한 search_path가 중요

 안전한 형태의 예:

   CREATE OR REPLACE FUNCTION trigger_lab.fn_secure_audit_orders()
   RETURNS trigger
   LANGUAGE plpgsql
   SECURITY DEFINER
   SET search_path = pg_catalog, trigger_lab, pg_temp
   AS $$
   BEGIN
       INSERT INTO trigger_lab.order_audit (...);
       RETURN NULL;
   END;
   $$;

 주의사항

   - SECURITY DEFINER가 꼭 필요한지 먼저 판단한다.
   - 함수 안의 테이블은 trigger_lab.order_audit처럼 스키마를 명시한다.
   - 신뢰할 수 없는 스키마가 먼저 탐색되지 않도록 search_path를 고정한다.
   - 함수 소유자와 함수 수정 권한을 엄격하게 관리한다.
*/


/*
===============================================================================
 21. 단순 규칙은 트리거보다 제약조건을 우선 사용
===============================================================================

 모든 자동 검증을 트리거로 만들 필요는 없다.

   요구사항                  우선 고려할 기능
   ----------------------------------------------------------------
   기본값 입력               DEFAULT
   필수값                    NOT NULL
   음수 방지                 CHECK
   중복 방지                 UNIQUE
   참조 무결성               FOREIGN KEY
   계산 컬럼                 Generated Column
   복잡한 변경 이력          Trigger 또는 CDC
   수정 시간 자동 기록       BEFORE UPDATE Trigger
   주기적인 대량 집계        배치 작업 또는 스케줄러

 제약조건은 테이블 정의에서 규칙을 바로 확인할 수 있고
 PostgreSQL이 데이터 무결성을 일관되게 보장한다.

 예:

   total_amount numeric(12, 2)
       CHECK (total_amount >= 0)

   email text
       UNIQUE

   customer_id bigint
       REFERENCES customers(customer_id)

 트리거는 다음처럼 제약조건만으로 표현하기 어려운 작업에 적합하다.

   - 변경 전후 전체 행을 감사 테이블에 기록
   - 주문 상태 변경 시 관련 업무 수행
   - 여러 테이블을 참조하는 복잡한 검증
   - 뷰의 INSERT / UPDATE / DELETE를 대신 처리
*/


/*
===============================================================================
 22. Constraint Trigger 개요
===============================================================================

 Constraint Trigger는 복잡한 무결성 검사를 제약조건처럼 처리하는
 고급 트리거다.

 특징

   - AFTER ROW 트리거로 작성한다.
   - DEFERRABLE로 선언할 수 있다.
   - INITIALLY DEFERRED를 사용하면 검사 시점을 트랜잭션 종료까지 미룰 수 있다.

 기본 형태:

   CREATE CONSTRAINT TRIGGER 트리거명
   AFTER INSERT OR UPDATE
   ON 테이블명
   DEFERRABLE INITIALLY DEFERRED
   FOR EACH ROW
   EXECUTE FUNCTION 트리거함수();

 단순한 CHECK, UNIQUE, FOREIGN KEY로 해결할 수 있다면
 내장 제약조건을 우선 사용한다.
*/


/*
===============================================================================
 23. Event Trigger 개요
===============================================================================

 지금까지의 트리거는 테이블 데이터의 변경을 감지하는 DML 트리거다.

 Event Trigger는 다음과 같은 DDL 사건을 감지한다.

   - CREATE TABLE
   - ALTER TABLE
   - DROP TABLE
   - 기타 DDL 명령

 Event Trigger 함수는 RETURNS trigger가 아니라
 RETURNS event_trigger로 선언한다.

 높은 권한이 필요하고 잘못 작성하면 DDL 실행을 방해할 수 있으므로
 아래 코드는 설명용으로만 제공하며 실행하지 않는다.

   CREATE OR REPLACE FUNCTION trigger_lab.fn_ddl_audit()
   RETURNS event_trigger
   LANGUAGE plpgsql
   AS $$
   BEGIN
       RAISE NOTICE 'DDL 태그: %', TG_TAG;
   END;
   $$;

   CREATE EVENT TRIGGER trg_ddl_audit
   ON ddl_command_end
   EXECUTE FUNCTION trigger_lab.fn_ddl_audit();

 Event Trigger에서 사용하는 대표 변수

   TG_EVENT
     - 발생한 이벤트 이름

   TG_TAG
     - CREATE TABLE, ALTER TABLE 등의 명령 태그
*/


/*
===============================================================================
 24. 트리거 설계 체크리스트
===============================================================================

 [기능]
  □ 트리거의 업무 목적이 명확한가?
  □ 제약조건이나 DEFAULT로 더 단순하게 해결할 수 없는가?
  □ BEFORE와 AFTER 중 목적에 맞는 시점을 선택했는가?
  □ ROW와 STATEMENT 중 목적에 맞는 단위를 선택했는가?
  □ NEW와 OLD를 사건에 맞게 사용했는가?
  □ UPDATE OF와 실제 값 변경 조건을 구분했는가?

 [성능]
  □ 벌크 INSERT 시 트리거 호출 횟수를 확인했는가?
  □ 행마다 무거운 SELECT나 UPDATE를 반복하지 않는가?
  □ WHEN 조건으로 불필요한 호출을 줄였는가?
  □ 전환 테이블과 집합 기반 처리를 검토했는가?
  □ EXPLAIN ANALYZE로 트리거 시간을 확인했는가?

 [안전성]
  □ 같은 테이블을 다시 수정해 재귀가 발생하지 않는가?
  □ 오류 발생 시 원본 SQL도 롤백된다는 점을 고려했는가?
  □ 여러 트리거의 실행 순서 의존성이 지나치게 복잡하지 않은가?
  □ SECURITY DEFINER 사용 시 search_path를 고정했는가?
  □ 트리거 비활성화 시 감사 및 무결성 누락을 검토했는가?

 [운영]
  □ 트리거 이름만 보고 목적과 실행 순서를 이해할 수 있는가?
  □ 트리거와 트리거 함수에 COMMENT를 작성했는가?
  □ 대량 적재 및 장애 상황을 테스트했는가?
  □ 트리거가 있다는 사실을 운영 문서에 기록했는가?
*/


/*
===============================================================================
 25. 최종 결과 확인
===============================================================================
*/

SELECT
    count(*) AS current_order_count
FROM orders;


SELECT
    operation,
    count(*) AS audit_count
FROM order_audit
GROUP BY operation
ORDER BY operation;


SELECT
    count(*) AS status_history_count
FROM order_status_history;


SELECT
    count(*) AS batch_log_count,
    sum(inserted_count) AS total_rows_seen_by_statement_trigger
FROM order_batch_log;


/*
===============================================================================
 26. 핵심 요약
===============================================================================

 1. PostgreSQL 트리거는 트리거 함수와 함께 동작한다.

 2. BEFORE 트리거는 저장 전에 NEW를 검증하거나 변경할 때 적합하다.

 3. AFTER 트리거는 감사 로그와 후속 작업에 적합하다.

 4. INSTEAD OF 트리거는 주로 뷰의 작업을 대신 처리한다.

 5. FOR EACH ROW는 행마다 실행되고,
    FOR EACH STATEMENT는 SQL 문장마다 한 번 실행된다.

 6. INSERT는 NEW, DELETE는 OLD, UPDATE는 NEW와 OLD를 사용한다.

 7. BEFORE 행 트리거에서 RETURN NULL은 해당 행 작업을 건너뛴다.
    AFTER 트리거의 반환값은 원본 행에 영향을 주지 않는다.

 8. 벌크 INSERT에서도 행 단위 트리거는 입력 행 수만큼 실행된다.
    COPY FROM도 트리거와 제약조건을 실행한다.

 9. 문장 단위 트리거와 전환 테이블을 사용하면
    변경된 여러 행을 집합 기반으로 처리할 수 있다.

10. 트리거와 원본 SQL은 같은 트랜잭션에 참여한다.
    트리거 오류 또는 ROLLBACK은 원본 작업과 트리거 작업 모두에 영향을 준다.

11. 단순한 무결성 규칙은 CHECK, UNIQUE, FOREIGN KEY 같은
    선언적 제약조건을 우선 사용한다.

12. 트리거는 편리하지만 자동으로 숨어서 실행되므로
    성능, 재귀, 실행 순서, 권한, 운영 가시성을 함께 고려해야 한다.

===============================================================================
*/
