/*
===============================================================================
 PostgreSQL 프로시저와 함수 — 기초부터 고급까지 통합 실습
===============================================================================
 권장 버전 : PostgreSQL 14 이상
 실습 도구 : DBeaver, pgAdmin, psql
 실습 방식 : 위에서 아래로 순서대로 실행

 핵심 구분
   - 함수(Function)    : SELECT 문 안에서 호출하고 값을 반환한다.
   - 프로시저(Procedure): CALL로 호출하고 업무 절차를 수행한다.
   - PostgreSQL 함수도 권한이 있으면 INSERT/UPDATE/DELETE가 가능하다.
   - COMMIT/ROLLBACK은 함수가 아니라, 조건을 만족하는 프로시저/DO에서만 가능하다.

 재실행 안내
   - 첫 부분에서 proc_lab 스키마를 삭제 후 다시 만들므로 전체 재실행이 가능하다.
   - 다른 실습 데이터와 분리된 전용 스키마를 사용한다.
===============================================================================
*/

-- ============================================================================
-- 00. 실습 환경 초기화
-- ============================================================================

DROP SCHEMA IF EXISTS proc_lab CASCADE;
CREATE SCHEMA proc_lab;

SET search_path TO proc_lab, public;

SELECT current_database() AS database_name,
       current_schema()   AS schema_name,
       version()          AS postgresql_version;


-- ============================================================================
-- 01. 테이블 생성 — 주문관리 업무 모델
-- ============================================================================

CREATE TABLE customers (
    customer_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name    varchar(100) NOT NULL,
    email            varchar(200) NOT NULL,
    email_normalized text GENERATED ALWAYS AS (lower(email)) STORED UNIQUE,
    customer_grade   varchar(10) NOT NULL DEFAULT 'BASIC'
                     CHECK (customer_grade IN ('BASIC', 'SILVER', 'GOLD', 'VIP')),
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE products (
    product_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name  varchar(120) NOT NULL,
    unit_price    numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    stock_qty     integer NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    active        boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE orders (
    order_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint NOT NULL REFERENCES customers(customer_id),
    order_status  varchar(20) NOT NULL DEFAULT 'PENDING'
                  CHECK (order_status IN
                         ('PENDING', 'PAID', 'SHIPPING', 'COMPLETED', 'CANCELLED')),
    total_amount  numeric(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    note          text,
    ordered_at    timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at    timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id    bigint NOT NULL REFERENCES products(product_id),
    quantity      integer NOT NULL CHECK (quantity > 0),
    unit_price    numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    line_amount   numeric(14,2)
                  GENERATED ALWAYS AS (quantity * unit_price) STORED,
    UNIQUE (order_id, product_id)
);

CREATE TABLE order_status_history (
    history_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    old_status   varchar(20),
    new_status   varchar(20) NOT NULL,
    changed_by   text NOT NULL DEFAULT current_user,
    changed_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE audit_log (
    audit_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   text NOT NULL,
    operation    text NOT NULL,
    row_id       bigint,
    old_data     jsonb,
    new_data     jsonb,
    changed_by   text NOT NULL DEFAULT current_user,
    changed_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE routine_error_log (
    log_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_name   text NOT NULL,
    error_state    text,
    error_message  text,
    error_detail   text,
    error_context  text,
    created_at     timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE transaction_demo_log (
    log_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message     text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);


--디스카운트 이벤트시에 멱등성 보장을 위한 배치 실행 이력 테이블
CREATE TABLE IF NOT EXISTS proc_lab.bulk_discount_runs (
    batch_key        text PRIMARY KEY,
    discount_percent numeric NOT NULL,
    min_price        numeric NOT NULL,
    affected_count   integer NOT NULL DEFAULT 0,
    run_status       text NOT NULL DEFAULT 'PROCESSING',
    started_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at     timestamptz,

    CONSTRAINT ck_bulk_discount_percent
        CHECK (discount_percent > 0 AND discount_percent <= 50),

    CONSTRAINT ck_bulk_discount_min_price
        CHECK (min_price >= 0),

    CONSTRAINT ck_bulk_discount_status
        CHECK (run_status IN ('PROCESSING', 'COMPLETED'))
);

CREATE INDEX idx_orders_customer_date
    ON orders (customer_id, ordered_at DESC);

CREATE INDEX idx_orders_status
    ON orders (order_status);

CREATE INDEX idx_order_items_order
    ON order_items (order_id);


-- ============================================================================
-- 02. 샘플 데이터 입력
-- ============================================================================

INSERT INTO customers
    (customer_id, customer_name, email, customer_grade)
VALUES
    (1, '김민준', 'minjun@example.com', 'GOLD'),
    (2, '이서연', 'seoyeon@example.com', 'VIP'),
    (3, '박지훈', 'jihoon@example.com', 'SILVER'),
    (4, '최유리', 'yuri@example.com', 'BASIC'),
    (5, '정도윤', 'doyun@example.com', 'GOLD');

INSERT INTO products
    (product_id, product_name, unit_price, stock_qty)
VALUES
    (1, '기계식 키보드', 89000, 100),
    (2, '무선 마우스',   49000, 150),
    (3, '27인치 모니터', 329000, 40),
    (4, 'USB-C 허브',    59000, 80),
    (5, '웹캠',          79000, 60);

INSERT INTO orders
    (order_id, customer_id, order_status, note, ordered_at)
VALUES
    (1, 1, 'PAID',      '오전 배송 희망', clock_timestamp() - interval '10 days'),
    (2, 2, 'SHIPPING',  NULL,             clock_timestamp() - interval '7 days'),
    (3, 1, 'PENDING',   '회사로 배송',     clock_timestamp() - interval '2 days'),
    (4, 3, 'COMPLETED', NULL,             clock_timestamp() - interval '20 days'),
    (5, 4, 'PENDING',   NULL,             clock_timestamp() - interval '1 day');

INSERT INTO order_items
    (order_id, product_id, quantity, unit_price)
VALUES
    (1, 1, 1,  89000),
    (1, 2, 2,  49000),
    (2, 3, 1, 329000),
    (3, 4, 2,  59000),
    (4, 5, 1,  79000),
    (5, 2, 1,  49000);

UPDATE orders AS o
SET total_amount = x.total_amount,
    updated_at   = clock_timestamp()
FROM (
    SELECT order_id, sum(line_amount) AS total_amount
    FROM order_items
    GROUP BY order_id
) AS x
WHERE x.order_id = o.order_id;

-- IDENTITY 열에 명시적인 ID를 넣었으므로 다음 자동 번호를 최댓값 뒤로 이동한다.
--운영 중 수시로 실행하는 코드가 아니라, 명시적 ID 입력이나 데이터 이관이 끝난 직후 한 번 실행하는 동기화 코드입니다.
---ex)---------------------------------------
--| 테이블       | 현재 최대 ID | 다음 자동 ID |
--| ---------- | -------:   | -------:  |
--| customers  |      100   |      101  |
--| products   |       50   |       51  |
--| orders     |    1,000   |    1,001  |

SELECT setval(
           pg_get_serial_sequence('proc_lab.customers', 'customer_id'),
           (SELECT max(customer_id) FROM customers),
           true			--최댓값이 이미 테이블에 존재(5)하는 현재 상황에서는 반드시 true가 적절합니다.
       );

SELECT setval(
           pg_get_serial_sequence('proc_lab.products', 'product_id'),
           (SELECT max(product_id) FROM products),
           true			--최댓값이 이미 테이블에 존재(5)하는 현재 상황에서는 반드시 true가 적절합니다.
       );

SELECT setval(
           pg_get_serial_sequence('proc_lab.orders', 'order_id'),
           (SELECT max(order_id) FROM orders),
           true			--최댓값이 이미 테이블에 존재(5)하는 현재 상황에서는 반드시 true가 적절합니다.
       );

SELECT * FROM customers ORDER BY customer_id;
SELECT * FROM products  ORDER BY product_id;
SELECT * FROM orders    ORDER BY order_id;
SELECT * FROM order_items    ORDER BY order_id;



-- ============================================================================
-- 24. 최종 확인
-- ============================================================================

SELECT 'customers' AS table_name, count(*) AS row_count FROM customers
UNION ALL
SELECT 'products', count(*) FROM products
UNION ALL
SELECT 'orders', count(*) FROM orders
UNION ALL
SELECT 'order_items', count(*) FROM order_items
UNION ALL
SELECT 'order_status_history', count(*) FROM order_status_history
UNION ALL
SELECT 'audit_log', count(*) FROM audit_log
UNION ALL
SELECT 'routine_error_log', count(*) FROM routine_error_log
ORDER BY table_name;


