-- ============================================================
-- PostgreSQL 학습용 skala_db >> app 샘플 스키마
-- 대상 database: skala_db
-- 대상 스키마: day02
-- PostgreSQL 13+ / DBeaver에서 전체 선택 후 한 번에 실행 가능
-- 주의: 기존 app 스키마와 그 안의 객체를 모두 삭제하고 다시 생성합니다.
-- ============================================================

BEGIN;

DROP SCHEMA IF EXISTS day02 CASCADE;
CREATE SCHEMA IF not exists day02;
SET search_path TO day02, public;


DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS majors CASCADE;

CREATE TABLE "students" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_no" varchar(20) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "email" varchar(200) UNIQUE NOT NULL,
  "major_id" int,
  "grade" smallint NOT NULL,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "majors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "credit" smallint NOT NULL
);

CREATE TABLE "enrollments" (
  "student_id" bigint,
  "course_id" int,
  "score" decimal(5,2),
  "enrolled_at" date NOT NULL,
  PRIMARY KEY ("student_id", "course_id")
);

COMMENT ON COLUMN "students"."id" IS 'PK';

COMMENT ON COLUMN "students"."student_no" IS '학번';

COMMENT ON COLUMN "students"."major_id" IS 'FK → 학과';

COMMENT ON COLUMN "students"."grade" IS '1~4학년';

ALTER TABLE "students" ADD FOREIGN KEY ("major_id") 
REFERENCES "majors" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("student_id") 
REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id") 
REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;



-- ① 학과 데이터 (majors)
INSERT INTO majors (code, name) VALUES
('CS', '컴퓨터공학과'),
('AI', '인공지능학과'),
('EE', '전자공학과'),
('BA', '경영학과');

-- ② 과목 데이터 (courses)
INSERT INTO courses (course_code, name, credit) VALUES
('CS101', 'Java 프로그래밍', 3),
('CS102', 'Python 프로그래밍', 3),
('DB201', '데이터베이스', 3),
('AI301', '머신러닝', 3),
('WEB101', '웹프로그래밍', 3),
('NET201', '컴퓨터네트워크', 3);

-- ③ 학생 데이터 (students) - null value 2개설정.
INSERT INTO students
(student_no, name, email, major_id, grade)
VALUES
('2024001','김철수','kim1@test.com',1,1),
('2024002','이영희','lee2@test.com',1,2),
('2024003','박민수','park3@test.com',2,3),
('2024004','최유리','choi4@test.com',2,4),
('2024005','정우성','jung5@test.com',3,2),
('2024006','한지민','han6@test.com',3,1),
('2024007','오세훈','oh7@test.com',4,3),
('2024008','김나영','kim8@test.com',4,4),
('2024009','서지훈','seo9@test.com',null,2),
('2024010','윤아름','yoon10@test.com',null,1);


-- ④ 수강 데이터 (enrollments) 학생마다 2과목씩 수강.
INSERT INTO enrollments
(student_id, course_id, score, enrolled_at)
VALUES
(1,1,95.5,'2025-03-02'),(1,3,91.0,'2025-03-02'),
(2,2,88.0,'2025-03-02'),(2,4,92.5,'2025-03-02'),
(3,1,76.0,'2025-03-02'),(3,5,81.5,'2025-03-02'),
(4,3,98.0,'2025-03-02'),(4,4,96.5,'2025-03-02'),
(5,2,79.0,'2025-03-02'),(5,6,85.5,'2025-03-02'),
(6,1,84.5,'2025-03-02'),(6,5,90.0,'2025-03-02'),
(7,4,89.5,'2025-03-02'),(7,6,91.0,'2025-03-02'),
(8,2,94.0,'2025-03-02'),(8,3,87.5,'2025-03-02'),
(9,1,83.0,'2025-03-02'),(9,4,80.0,'2025-03-02'),
(10,5,93.5,'2025-03-02'),(10,6,97.0,'2025-03-02'),
(1,2,88.0,'2025-09-01'),(1,4,92.5,'2025-09-01'),
(2,1,95.5,'2025-09-01'),(2,3,91.0,'2025-09-01')
ON CONFLICT (student_id, course_id)
DO NOTHING;


COMMIT;
























