/*
===============================================================================
 PostgreSQL 프로시저와 함수 — 기초부터 고급까지 통합 실습
===============================================================================
 권장 버전 : PostgreSQL 14 이상
 실습 도구 : DBeaver, pgAdmin, psql
 실습 방식 : 위에서 아래로 순서대로 실행

 핵심 구분
   - 함수(Function)    : SELECT 문 안에서 호출하고 값을 반환한다.
   - 프로시저(Procedure): CALL로 호출하고 업무 절차를 수행한다.
   - PostgreSQL 함수도 권한이 있으면 INSERT/UPDATE/DELETE가 가능하다.
   - COMMIT/ROLLBACK은 함수가 아니라, 조건을 만족하는 프로시저/DO에서만 가능하다.

 재실행 안내
   - 첫 부분에서 proc_lab 스키마를 삭제 후 다시 만들므로 전체 재실행이 가능하다.
   - 다른 실습 데이터와 분리된 전용 스키마를 사용한다.
===============================================================================
*/

-- ============================================================================
-- 00. 실습 환경 초기화
-- ============================================================================

DROP SCHEMA IF EXISTS proc_lab CASCADE;
CREATE SCHEMA proc_lab;

SET search_path TO proc_lab, public;

SELECT current_database() AS database_name,
       current_schema()   AS schema_name,
       version()          AS postgresql_version;


-- ============================================================================
-- 01. 테이블 생성 — 주문관리 업무 모델
-- ============================================================================

CREATE TABLE customers (
    customer_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name    varchar(100) NOT NULL,
    email            varchar(200) NOT NULL,
    email_normalized text GENERATED ALWAYS AS (lower(email)) STORED UNIQUE,
    customer_grade   varchar(10) NOT NULL DEFAULT 'BASIC'
                     CHECK (customer_grade IN ('BASIC', 'SILVER', 'GOLD', 'VIP')),
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE products (
    product_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name  varchar(120) NOT NULL,
    unit_price    numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    stock_qty     integer NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    active        boolean NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE orders (
    order_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint NOT NULL REFERENCES customers(customer_id),
    order_status  varchar(20) NOT NULL DEFAULT 'PENDING'
                  CHECK (order_status IN
                         ('PENDING', 'PAID', 'SHIPPING', 'COMPLETED', 'CANCELLED')),
    total_amount  numeric(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    note          text,
    ordered_at    timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at    timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      bigint NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id    bigint NOT NULL REFERENCES products(product_id),
    quantity      integer NOT NULL CHECK (quantity > 0),
    unit_price    numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    line_amount   numeric(14,2)
                  GENERATED ALWAYS AS (quantity * unit_price) STORED,
    UNIQUE (order_id, product_id)
);

CREATE TABLE order_status_history (
    history_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     bigint NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    old_status   varchar(20),
    new_status   varchar(20) NOT NULL,
    changed_by   text NOT NULL DEFAULT current_user,
    changed_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE audit_log (
    audit_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   text NOT NULL,
    operation    text NOT NULL,
    row_id       bigint,
    old_data     jsonb,
    new_data     jsonb,
    changed_by   text NOT NULL DEFAULT current_user,
    changed_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE routine_error_log (
    log_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_name   text NOT NULL,
    error_state    text,
    error_message  text,
    error_detail   text,
    error_context  text,
    created_at     timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE transaction_demo_log (
    log_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message     text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);


--디스카운트 이벤트시에 멱등성 보장을 위한 배치 실행 이력 테이블
CREATE TABLE IF NOT EXISTS proc_lab.bulk_discount_runs (
    batch_key        text PRIMARY KEY,
    discount_percent numeric NOT NULL,
    min_price        numeric NOT NULL,
    affected_count   integer NOT NULL DEFAULT 0,
    run_status       text NOT NULL DEFAULT 'PROCESSING',
    started_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at     timestamptz,

    CONSTRAINT ck_bulk_discount_percent
        CHECK (discount_percent > 0 AND discount_percent <= 50),

    CONSTRAINT ck_bulk_discount_min_price
        CHECK (min_price >= 0),

    CONSTRAINT ck_bulk_discount_status
        CHECK (run_status IN ('PROCESSING', 'COMPLETED'))
);

CREATE INDEX idx_orders_customer_date
    ON orders (customer_id, ordered_at DESC);

CREATE INDEX idx_orders_status
    ON orders (order_status);

CREATE INDEX idx_order_items_order
    ON order_items (order_id);


-- ============================================================================
-- 02. 샘플 데이터 입력
-- ============================================================================

INSERT INTO customers
    (customer_id, customer_name, email, customer_grade)
VALUES
    (1, '김민준', 'minjun@example.com', 'GOLD'),
    (2, '이서연', 'seoyeon@example.com', 'VIP'),
    (3, '박지훈', 'jihoon@example.com', 'SILVER'),
    (4, '최유리', 'yuri@example.com', 'BASIC'),
    (5, '정도윤', 'doyun@example.com', 'GOLD');

INSERT INTO products
    (product_id, product_name, unit_price, stock_qty)
VALUES
    (1, '기계식 키보드', 89000, 100),
    (2, '무선 마우스',   49000, 150),
    (3, '27인치 모니터', 329000, 40),
    (4, 'USB-C 허브',    59000, 80),
    (5, '웹캠',          79000, 60);

INSERT INTO orders
    (order_id, customer_id, order_status, note, ordered_at)
VALUES
    (1, 1, 'PAID',      '오전 배송 희망', clock_timestamp() - interval '10 days'),
    (2, 2, 'SHIPPING',  NULL,             clock_timestamp() - interval '7 days'),
    (3, 1, 'PENDING',   '회사로 배송',     clock_timestamp() - interval '2 days'),
    (4, 3, 'COMPLETED', NULL,             clock_timestamp() - interval '20 days'),
    (5, 4, 'PENDING',   NULL,             clock_timestamp() - interval '1 day');

INSERT INTO order_items
    (order_id, product_id, quantity, unit_price)
VALUES
    (1, 1, 1,  89000),
    (1, 2, 2,  49000),
    (2, 3, 1, 329000),
    (3, 4, 2,  59000),
    (4, 5, 1,  79000),
    (5, 2, 1,  49000);

UPDATE orders AS o
SET total_amount = x.total_amount,
    updated_at   = clock_timestamp()
FROM (
    SELECT order_id, sum(line_amount) AS total_amount
    FROM order_items
    GROUP BY order_id
) AS x
WHERE x.order_id = o.order_id;

-- IDENTITY 열에 명시적인 ID를 넣었으므로 다음 자동 번호를 최댓값 뒤로 이동한다.
SELECT setval(
           pg_get_serial_sequence('proc_lab.customers', 'customer_id'),
           (SELECT max(customer_id) FROM customers),
           true
       );

SELECT setval(
           pg_get_serial_sequence('proc_lab.products', 'product_id'),
           (SELECT max(product_id) FROM products),
           true
       );

SELECT setval(
           pg_get_serial_sequence('proc_lab.orders', 'order_id'),
           (SELECT max(order_id) FROM orders),
           true
       );

SELECT * FROM customers ORDER BY customer_id;
SELECT * FROM products  ORDER BY product_id;
SELECT * FROM orders    ORDER BY order_id;
SELECT * FROM order_items    ORDER BY order_id;


-- ============================================================================
-- 03. [기초 함수] LANGUAGE SQL — 한 개의 계산값 반환
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_tax_amount(
    p_amount   numeric,
    p_tax_rate numeric DEFAULT 0.10
)
RETURNS numeric		--numeric형식으로 결과 반환
LANGUAGE sql		--sql로 작성
immutable			--같은 입력값을 전달하면 데이터베이스 상태나 시간에 관계없이 항상 같은 결과를 반환한다는 선언입니다.
strict				--입력값이 NULL이면 함수 본문을 실행하지 않고 NULL 반환
--| 구분          | 같은 입력의 결과        |    테이블 조회 | DML |
--| ----------- | ------------------- | ----------: | --: |
--| `IMMUTABLE` | 항상 동일             | 원칙적으로 부적합 |  불가 |
--| `STABLE`    | 한 SQL 문 안에서 동일   |        가능   |  불가 |
--| `VOLATILE`  | 실행할 때마다 달라질 수 있음 |        가능 |  가능 |
AS $function$
    SELECT round(p_amount * p_tax_rate, 2);
$function$;

COMMENT ON FUNCTION fn_tax_amount(numeric, numeric)
IS '금액과 세율로 세액을 계산하는 순수 계산 함수';

SELECT proc_lab.fn_tax_amount(100000)       AS tax_default_10_percent;
SELECT proc_lab.fn_tax_amount(100000, 0.08) AS tax_8_percent;
SELECT proc_lab.fn_tax_amount(NULL, 0.10)   AS strict_returns_null;


-- ============================================================================
-- 04. [기초 함수] LANGUAGE plpgsql — 변수, IF, 예외 발생
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_line_total(
    p_unit_price       numeric,
    p_quantity         integer,
    p_discount_percent numeric DEFAULT 0
)
RETURNS numeric
LANGUAGE plpgsql
IMMUTABLE
STRICT
AS $function$
DECLARE
    v_subtotal numeric;
    v_result   numeric;
BEGIN
    IF p_unit_price < 0 THEN
        RAISE EXCEPTION '단가는 0 이상이어야 합니다: %', p_unit_price
            USING ERRCODE = '22003';
    END IF;

    IF p_quantity <= 0 THEN
        RAISE EXCEPTION '수량은 1 이상이어야 합니다: %', p_quantity
            USING ERRCODE = '22003';
    END IF;

    IF p_discount_percent NOT BETWEEN 0 AND 100 THEN
        RAISE EXCEPTION '할인율은 0~100 범위여야 합니다: %',
                        p_discount_percent
            USING ERRCODE = '22003';
    END IF;

    v_subtotal := p_unit_price * p_quantity;
    v_result   := v_subtotal * (1 - p_discount_percent / 100.0);

    RETURN round(v_result, 2);
END;
$function$;

SELECT proc_lab.fn_line_total(50000, 2)     AS no_discount;
SELECT proc_lab.fn_line_total(50000, 2, 10) AS discount_10_percent;


-- ============================================================================
-- 05. [중급 함수] 테이블을 조회하여 단일 값 반환
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_customer_order_total(
    p_customer_id bigint
)
RETURNS numeric
LANGUAGE sql
STABLE
STRICT
AS $function$
    SELECT coalesce(sum(o.total_amount), 0)::numeric(14,2)
    FROM proc_lab.orders AS o
    WHERE o.customer_id = p_customer_id
      AND o.order_status <> 'CANCELLED';
$function$;

SELECT c.customer_id,
       c.customer_name,
       proc_lab.fn_customer_order_total(c.customer_id) AS cumulative_order_amount
FROM customers AS c
ORDER BY c.customer_id;


-- ============================================================================
-- 06. [중급 함수] 여러 행 반환 — RETURNS TABLE + RETURN QUERY
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_orders_by_status(
    p_status text DEFAULT NULL
)
RETURNS TABLE (
    order_id      bigint,
    customer_name varchar,
    order_status  varchar,
    total_amount  numeric,
    ordered_at    timestamptz
)
LANGUAGE plpgsql
STABLE
AS $function$
BEGIN
    RETURN QUERY
    SELECT o.order_id,
           c.customer_name,
           o.order_status,
           o.total_amount,
           o.ordered_at
    FROM proc_lab.orders AS o
    JOIN proc_lab.customers AS c
      ON c.customer_id = o.customer_id
    WHERE p_status IS NULL
       OR o.order_status = p_status
    ORDER BY o.ordered_at DESC;
END;
$function$;

SELECT * FROM proc_lab.fn_orders_by_status();
SELECT * FROM proc_lab.fn_orders_by_status('PENDING');


-- ============================================================================
-- 07. [중급 함수] %ROWTYPE, SELECT INTO STRICT, 예외 변환
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_find_order(
    p_order_id bigint
)
RETURNS proc_lab.orders
LANGUAGE plpgsql
STABLE
STRICT
AS $function$
DECLARE
    v_order proc_lab.orders%ROWTYPE;
BEGIN
    SELECT o.*
      INTO STRICT v_order
      FROM proc_lab.orders AS o
     WHERE o.order_id = p_order_id;

    RETURN v_order;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE EXCEPTION '주문번호 %를 찾을 수 없습니다.', p_order_id
            USING ERRCODE = 'P0002',
                  HINT = 'orders 테이블의 order_id를 확인하세요.';
END;
$function$;

SELECT (proc_lab.fn_find_order(1)).*;

-- 오류 실습: 아래 문장의 주석을 해제하여 사용자 정의 오류를 확인한다.
-- SELECT (fn_find_order(999999)).*;


-- ============================================================================
-- 08. [중급 함수] 함수도 DML 가능 — 재고 차감 후 남은 수량 반환
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_reserve_stock(
    p_product_id bigint,
    p_quantity   integer
)
RETURNS integer
LANGUAGE plpgsql
VOLATILE
STRICT
AS $function$
DECLARE
    v_remaining integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION '차감 수량은 1 이상이어야 합니다.'
            USING ERRCODE = '22003';
    END IF;

    UPDATE proc_lab.products
       SET stock_qty = stock_qty - p_quantity
     WHERE product_id = p_product_id
       AND active
       AND stock_qty >= p_quantity
    RETURNING stock_qty INTO v_remaining;

    IF NOT FOUND THEN
        RAISE EXCEPTION '상품 %의 재고가 부족하거나 비활성 상태입니다.',
                        p_product_id
            USING ERRCODE = 'P0001';
    END IF;

    RETURN v_remaining;
END;
$function$;

SELECT proc_lab.fn_reserve_stock(5, 50) AS remaining_stock;
SELECT product_id, product_name, stock_qty
FROM products
WHERE product_id = 1;


-- ============================================================================
-- 09. [기초 프로시저] 주문 생성 — CALL + INOUT
-- ============================================================================
--고객이 상품을 주문하면 상품 가격과 재고를 확인하고, 
--재고를 차감한 뒤 주문 헤더와 주문 상세를 생성하여 
--새 주문번호를 돌려주는 프로시저입니다.
--| 매개변수            | 모드      | 의미                         |
--| --------------- | ------- | -------------------------- |
--| `p_customer_id` | `IN`    | 주문할 고객번호                   |
--| `p_product_id`  | `IN`    | 주문할 상품번호                   |
--| `p_quantity`    | `IN`    | 주문수량                       |
--| `p_order_id`    | `INOUT` | 호출할 때 값을 받고, 처리 후 주문번호를 반환 |

CREATE OR REPLACE PROCEDURE proc_lab.pr_create_order(
    IN    p_customer_id bigint,
    IN    p_product_id  bigint,
    IN    p_quantity    integer,
    INOUT p_order_id    bigint DEFAULT NULL
)
LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_unit_price products.unit_price%TYPE; --상품 단가를 저장하는 지역변수
BEGIN
	RAISE NOTICE '고객번호: %', p_customer_id;
	RAISE NOTICE '상품번호: %', p_product_id;
	RAISE NOTICE '주문수량: %', p_quantity;
	--주문수량 검증
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION '주문 수량은 1 이상이어야 합니다.'
            USING ERRCODE = '22003';
    END IF;

	--주문할 상품의 단가 조회
    SELECT p.unit_price
      INTO STRICT v_unit_price   --조회된 상품 가격은 v_unit_price에 저장됩니다.STRICT가 있기 때문에 반드시 한 건이 조회되어야 합니다
      FROM proc_lab.products AS p
     WHERE p.product_id = p_product_id
       AND p.active;
	RAISE NOTICE '상품단가: %', v_unit_price;

    -- 함수가 DML을 수행하고 남은 재고를 반환한다.
	-- fn_reserve_stock() 함수를 호출하여 재고를 예약하거나 차감합니다.
	-- PERFORM은 PL/pgSQL에서 함수의 반환값을 사용하지 않고 함수만 실행할 때 사용합니다.
    PERFORM proc_lab.fn_reserve_stock(p_product_id, p_quantity);

	--주문 헤더 생성
	--orders 테이블에 주문의 기본 정보를 입력합니다.
    INSERT INTO proc_lab.orders (customer_id, order_status, total_amount)
    VALUES (
        p_customer_id,
        'PENDING',
        proc_lab.fn_line_total(v_unit_price, p_quantity) --할인처리함수호출
    )
    RETURNING order_id INTO p_order_id;
	--RETURNING의 역할 : 새롭게 생성된 주문번호를 바로 받아옵니다.예)p_order_id = 15
	-- 별도로 다시 조회할 필요가 없습니다.


	--order_items 테이블에 주문한 상품의 상세 내용을 입력합니다.
--	현재 프로시저는 상품번호를 하나만 받기 때문에 한 번 호출할 때 한 종류의 상품만 주문할 수 있는 구조입니다.
--	order_id   = 15
--	product_id = 2
--	quantity   = 2
--	unit_price = 50000
    INSERT INTO proc_lab.order_items
        (order_id, product_id, quantity, unit_price)
    VALUES
        (p_order_id, p_product_id, p_quantity, v_unit_price);

--	주문번호 출력 : % 자리에 p_order_id 값이 들어갑니다.
    RAISE NOTICE '새 주문번호: %', p_order_id;
END;
$procedure$;

--프로시저를 proc_lab 스키마에 확실히 만들려면 선언과 호출도 다음처럼 스키마를 지정하는 것이 안전합니다.
CALL proc_lab.pr_create_order(1, 2, 2, NULL);
--고객번호: 1
--상품번호: 2
--주문수량: 2개
--주문번호: 처음에는 모르므로 NULL
--주문이 등록되면 새 주문번호가 p_order_id에 저장됨

SELECT *
FROM orders
ORDER BY order_id DESC
LIMIT 3;


-- ============================================================================
-- 10. [중급 프로시저] 상태 변경 — OUT 매개변수 + GET DIAGNOSTICS
-- ============================================================================

CREATE OR REPLACE PROCEDURE pr_change_order_status(
    IN  p_order_id   bigint,  	--상태를 변경할 주문번호 3
    IN  p_new_status text,		--새롭게 적용할 주문 상태 PAID
    OUT p_message    text		--처리 결과 메시지 반환 NULL
)
LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_old_status orders.order_status%TYPE; --지역변수 선언 : 변경 전 주문 상태를 저장합니다.
    v_row_count  integer;  	--UPDATE로 실제 변경된 행의 개수를 저장(0,1)
BEGIN
--다음 다섯 가지 상태만 허용합니다.
--PENDING   : 주문 대기
--PAID      : 결제 완료
--SHIPPING  : 배송 중
--COMPLETED : 주문 완료
--CANCELLED : 주문 취소
    IF p_new_status IS NULL
	   OR p_new_status NOT IN
	      ('PENDING', 'PAID', 'SHIPPING', 'COMPLETED', 'CANCELLED') THEN
	    RAISE EXCEPTION '허용되지 않은 주문 상태입니다: %',
	                    COALESCE(p_new_status, 'NULL')
	        USING ERRCODE = '22023';
	END IF;

--  현재 주문 상태 조회
    SELECT order_status
      INTO STRICT v_old_status   --주문번호에 해당하는 현재 상태를 조회해서 v_old_status에 저장합니다.
      FROM proc_lab.orders
     WHERE order_id = p_order_id
     FOR UPDATE;  --조회한 주문 행을 잠급니다. 잠금은 일반적으로 트랜잭션이 COMMIT 또는 ROLLBACK될 때 해제됩니다.
--INTO STRICT : 조회 결과가 반드시 한 건이어야 한다는 뜻입니다.
--
--조회 결과 1건: 정상적으로 변수에 저장
--조회 결과 0건: NO_DATA_FOUND 오류
--조회 결과 2건 이상: TOO_MANY_ROWS 오류
--
--order_id가 기본키라면 여러 건이 조회될 가능성은 없으므로, 주로 존재하지 않는 주문번호를 검사하는 효과가 있습니다.


--주문 상태 변경 - 주문 상태와 수정 시간을 변경합니다.
--clock_timestamp()와 now() 차이
--now(): 현재 트랜잭션이 시작된 시각
--clock_timestamp(): 함수가 호출되는 실제 현재 시각
--
--프로시저 내부 작업의 정확한 실행 시각을 기록하려면 clock_timestamp()가 적합합니다.
    UPDATE proc_lab.orders
       SET order_status = p_new_status,   --새로운 주문 상태를 저장합니다.
           updated_at   = clock_timestamp()   --실제로 UPDATE가 실행되는 현재 시각을 기록합니다.
     WHERE order_id = p_order_id
       AND order_status IS DISTINCT FROM p_new_status; --기존 상태와 새 상태가 다를 때만 UPDATE합니다.
								--예를 들어:기존 상태 PENDING, 새 상태 PAID → 서로 다름 → UPDATE 실행
								--<>와 비슷하지만 NULL까지 안전하게 비교할 수 있다는 차이가 있습니다.

--UPDATE된 행 개수 확인
    GET DIAGNOSTICS v_row_count = ROW_COUNT;

	RAISE NOTICE '변경 전 상태: %', v_old_status;
	RAISE NOTICE '변경 요청 상태: %', p_new_status;
	RAISE NOTICE 'UPDATE 행 개수: %', v_row_count;

    IF v_row_count = 0 THEN
        p_message := format('주문 %s는 이미 %s 상태입니다.',
                            p_order_id, p_new_status);
        RETURN;
    END IF;



    INSERT INTO proc_lab.order_status_history
        (order_id, old_status, new_status)
    VALUES
        (p_order_id, v_old_status, p_new_status);

    p_message := format('주문 %s: %s → %s 변경 완료',
                        p_order_id, v_old_status, p_new_status);
END;
$procedure$;

--주문 상태를 변경하고, 실제로 상태가 변경된 경우에만 변경 이력을 저장한 뒤 처리 결과 메시지를 반환합니다.
-- OUT 매개변수 자리에는 SQL에서 보통 NULL을 전달한다.
CALL pr_change_order_status(3, 'PAID', NULL);

SELECT * FROM order_status_history ORDER BY history_id;


-- ============================================================================
-- 11. [중급 프로시저] UPSERT — 이메일 기준 고객 등록/수정
-- ============================================================================

CREATE OR REPLACE PROCEDURE proc_lab.pr_upsert_customer(
    IN    p_customer_name  varchar,		--등록하거나 수정할 고객명
    IN    p_email          varchar,		--고객을 식별하는 이메일
    INOUT p_customer_id    bigint DEFAULT null	--신규 또는 기존 고객번호 반환
)
LANGUAGE plpgsql
AS $procedure$
BEGIN
--고객명 필수 검사 : nullif()>> NULL차단,btrim()의 역할 >> 문자열 양쪽의 공백을 제거합니다.
    IF nullif(btrim(p_customer_name), '') IS NULL THEN
        RAISE EXCEPTION '고객명은 필수입니다.'
            USING ERRCODE = '23502';
    END IF;


--이메일 형식 검사
--PostgreSQL 정규표현식 연산자입니다.
--| 연산자   | 의미                |
--| ----- | ----------------- |
--| `~`   | 대소문자를 구분하여 일치     |
--| `~*`  | 대소문자를 구분하지 않고 일치  |
--| `!~`  | 대소문자를 구분하여 불일치    |
--| `!~*` | 대소문자를 구분하지 않고 불일치 |

--| 표현식              | 정규표현식 해석     |
--| ---------------- | --------------- |
--| `^`              | 문자열 시작          |
--| `[A-Z0-9._%+-]+` | 이메일 아이디 부분      |
--| `@`              | @ 문자            |
--| `[A-Z0-9.-]+`    | 도메인 부분          |
--| `\.`             | 점 문자            |
--| `[A-Z]{2,}`      | 2글자 이상의 최상위 도메인 |
--| `$`              | 문자열 끝           |
	
	IF nullif(btrim(p_email), '') IS NULL THEN
	    RAISE EXCEPTION '이메일은 필수입니다.'
	        USING ERRCODE = '23502';
	END IF;
	
	IF btrim(p_email) !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' THEN
        RAISE EXCEPTION '올바른 이메일 형식이 아닙니다: %', p_email
            USING ERRCODE = '22023';
    END IF;

--같은 이메일이 없으면 INSERT, 이미 있으면 UPDATE하고 고객번호를 반환합니다.
--EXCLUDED는 원래 INSERT하려고 했지만 중복으로 인해 제외된 새로운 데이터를 의미합니다.
    INSERT INTO proc_lab.customers (customer_name, email)
    VALUES (btrim(p_customer_name), btrim(p_email))
    ON CONFLICT (email_normalized) 		--email_normalized 값이 중복되면 INSERT하지 않고 DO UPDATE를 실행합니다.
    DO UPDATE
       SET customer_name = EXCLUDED.customer_name,
           email         = EXCLUDED.email,
           active        = true		--기존 고객이 탈퇴 또는 비활성 상태여도 같은 이메일로 다시 등록하면 활성 고객으로 복구합니다.
    RETURNING customer_id INTO p_customer_id;
END;
$procedure$;

--이 프로시저는 고객 이메일을 기준으로 고객을 신규 등록하거나, 이미 존재하면 고객정보를 수정하는 UPSERT 프로시저입니다.
CALL proc_lab.pr_upsert_customer('한지민', 'jimin@example.com', NULL);
CALL proc_lab.pr_upsert_customer('한지민(수정)', 'JIMIN@example.com', NULL);
--
--1. 고객명 검사 통과
--2. 이메일 형식 검사 통과
--3. email_normalized 중복 발견
--4. INSERT 대신 UPDATE
--5. 고객명과 이메일 수정
--6. 기존 customer_id 반환

SELECT customer_id, customer_name, email, email_normalized
FROM customers
WHERE email_normalized = 'jimin@example.com';
--p_customer_id
---------------
--			6
--[[[멱등성과의 관계]]]
--이 프로시저는 동일한 이메일을 여러 번 호출해도 고객 행이 계속 추가되지 않습니다.
--다만 동일한 값이어도 DO UPDATE 자체는 실행됩니다



-- ============================================================================
-- 12. [중급 프로시저] 반복문 — 행마다 별도 판단이 필요한 경우
-- ============================================================================

CREATE OR REPLACE PROCEDURE pr_restock_low_inventory(
    IN  p_threshold integer,		--재고 부족 판단 기준
    IN  p_add_qty   integer,		--상품마다 추가할 재고
    OUT p_affected  integer			--재고를 보충한 상품 개수  <<OUT 매개변수 자리
)
LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_product products%ROWTYPE; --products 테이블의 한 행 전체를 저장할 수 있는 변수입니다.
--다음처럼 모든 컬럼을 사용할 수 있습니다.
--v_product.product_id
--v_product.product_name
--v_product.stock_qty
--v_product.unit_price
--v_product.active
BEGIN
--입력값 검증
    IF p_threshold < 0 OR p_add_qty <= 0 THEN
        RAISE EXCEPTION '기준 재고는 0 이상, 추가 수량은 1 이상이어야 합니다.';
    END IF;

--NULL 검증 보완
	IF p_threshold IS NULL
	   OR p_add_qty IS NULL
	   OR p_threshold < 0
	   OR p_add_qty <= 0 THEN
	
	    RAISE EXCEPTION
	        '기준 재고는 0 이상, 추가 수량은 1 이상이어야 합니다.'
	        USING ERRCODE = '22023';
	END IF;

    p_affected := 0; --처리 건수 초기화 : 재고를 보충한 상품 수를 저장할 출력 매개변수를 0으로 초기화합니다.


--재고 부족 상품 조회
    FOR v_product IN
        SELECT *
        FROM proc_lab.products
        WHERE active    -- active = true 와 같은 표현으로 활성 상품만 대상으로 합니다.
          AND stock_qty < p_threshold		--현재 재고가 기준치보다 작은 상품만 조회합니다.
        ORDER BY product_id				--상품번호 순서로 처리합니다.
        FOR UPDATE		--조회한 상품 행을 잠급니다.재고처럼 동시 변경 가능성이 높은 데이터에서는 중요한 처리입니다.
    LOOP
        UPDATE proc_lab.products
           SET stock_qty = stock_qty + p_add_qty		--상품별 재고 증가
         WHERE product_id = v_product.product_id;	--v_product.product_id는 현재 반복 중인 상품번호입니다.

        p_affected := p_affected + 1;		--상품 하나를 처리할 때마다 출력값을 1씩 증가시킵니다.
		RAISE NOTICE '처리: % 건',
                     p_affected;

        RAISE NOTICE '% 재고 보충: % → %',
                     v_product.product_name,
                     v_product.stock_qty,
                     v_product.stock_qty + p_add_qty;
    END LOOP;
END;
$procedure$;


--활성 상품 중 재고가 기준치보다 적은 상품을 찾아, 각 상품의 재고를 지정한 수량만큼 추가하고 
--처리한 상품 개수를 반환합니다.
--현재 재고가 70개 미만
--활성 상태인 상품을 찾아
--상품마다 재고 20개 추가
--처리한 상품 수를 p_affected로 반환
CALL pr_restock_low_inventory(70, 20, NULL);

-- 단순히 같은 값을 일괄 변경한다면 반복문보다 아래와 같은 집합 기반 UPDATE가 좋다.
-- UPDATE products SET stock_qty = stock_qty + 20 WHERE active AND stock_qty < 70;


-- ============================================================================
-- 13. [중급 프로시저] 집합 기반 배치 — 가격 일괄 할인
-- ============================================================================

CREATE OR REPLACE PROCEDURE proc_lab.pr_bulk_discount(
    IN  p_discount_percent numeric,  	--상품에 적용할 할인율
    IN  p_min_price        numeric,		--할인 대상이 되는 최소 가격
    OUT p_affected         integer		--가격이 변경된 상품 개수
)
LANGUAGE plpgsql
AS $procedure$
BEGIN
--NULL과 할인율 유효성 검사 : 할인율은 0% 초과 50% 이하만 허용합니다.
    IF p_discount_percent IS NULL
	   OR p_discount_percent <= 0
	   OR p_discount_percent > 50 THEN
	    RAISE EXCEPTION
	        '배치 할인율은 0 초과 50 이하이어야 합니다.'
	        USING ERRCODE = '22023';
	END IF;

--NULL과 최소 가격 검증 보완
	IF p_min_price IS NULL OR p_min_price < 0 THEN
        RAISE EXCEPTION
            '최소 가격은 0 이상이어야 합니다.'
            USING ERRCODE = '22023';
    END IF;

--상품 가격 일괄 변경 : 반복문 없이 조건에 맞는 모든 상품 가격을 한 번의 UPDATE로 변경합니다.
    UPDATE proc_lab.products
       SET unit_price = round(
           unit_price * (1 - p_discount_percent / 100.0),
           2
       )
     WHERE active = true  --비활성 상품은 가격을 변경하지 않습니다.
       AND unit_price >= p_min_price;

-- GET DIAGNOSTICS : 위에 업데이트쿼리와 아래 사이에 다른 쿼리가 들어오면 그 처리 행 개수를 반환할 수 있으니 주의하세요
    GET DIAGNOSTICS p_affected = ROW_COUNT; --바로 전에 실행한 UPDATE가 처리한 행 개수를 가져옵니다.
END;
$procedure$;

--활성 상품 중 가격이 기준 금액 이상인 모든 상품에 동일한 할인율을 한꺼번에 적용하고, 변경된 상품 개수를 반환합니다.
--할인율: 5%
--할인 대상: 가격이 100,000원 이상
--활성 상품만 처리
--처리한 상품 개수를 p_affected로 반환
CALL proc_lab.pr_bulk_discount(5, 100000, NULL); --1.멱등성 처리없는 프로시저 호출

SELECT product_id, product_name, unit_price,stock_qty,active FROM products ORDER BY product_id;


--2. 멱등성 적용 프로시저
--기존 프로시저와 혼동하지 않도록 새로운 이름으로 작성했습니다.
CREATE OR REPLACE PROCEDURE proc_lab.pr_bulk_discount_idempotent(
    IN  p_batch_key        text,
    IN  p_discount_percent numeric,
    IN  p_min_price        numeric,
    OUT p_affected         integer
)
LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_batch_key      text;
    v_claimed        integer;
    v_saved_discount numeric;
    v_saved_min_price numeric;
    v_saved_affected integer;
    v_saved_status   text;
BEGIN
    ----------------------------------------------------------------
    -- 1. 입력값 정리 및 검증
    ----------------------------------------------------------------
    v_batch_key := btrim(p_batch_key);

    IF v_batch_key IS NULL OR v_batch_key = '' THEN
        RAISE EXCEPTION '배치 키는 필수입니다.'
            USING ERRCODE = '23502';
    END IF;

    IF p_discount_percent IS NULL
       OR p_discount_percent <= 0
       OR p_discount_percent > 50 THEN
        RAISE EXCEPTION
            '배치 할인율은 0 초과 50 이하이어야 합니다.'
            USING ERRCODE = '22023';
    END IF;

    IF p_min_price IS NULL OR p_min_price < 0 THEN
        RAISE EXCEPTION
            '최소 가격은 0 이상이어야 합니다.'
            USING ERRCODE = '22023';
    END IF;

    ----------------------------------------------------------------
    -- 2. 배치 키 선점
    --    동일한 배치 키가 없을 때만 1건 INSERT된다.
    ----------------------------------------------------------------
    INSERT INTO proc_lab.bulk_discount_runs (
        batch_key,
        discount_percent,
        min_price,
        affected_count,
        run_status
    )
    VALUES (
        v_batch_key,
        p_discount_percent,
        p_min_price,
        0,
        'PROCESSING'
    )
    ON CONFLICT (batch_key)
    DO NOTHING;

    GET DIAGNOSTICS v_claimed = ROW_COUNT;

    ----------------------------------------------------------------
    -- 3. 이미 존재하는 배치 키이면 기존 실행 결과 반환
    ----------------------------------------------------------------
    IF v_claimed = 0 THEN
        SELECT
            discount_percent,
            min_price,
            affected_count,
            run_status
        INTO STRICT
            v_saved_discount,
            v_saved_min_price,
            v_saved_affected,
            v_saved_status
        FROM proc_lab.bulk_discount_runs
        WHERE batch_key = v_batch_key
        FOR UPDATE;

        -- 같은 배치 키를 다른 조건으로 사용하지 못하게 검사
--		기존에는 할인율 5%로 사용한 배치 키인데 10%로 다시 요청하면 오류가 발생합니다.
        IF v_saved_discount IS DISTINCT FROM p_discount_percent
           OR v_saved_min_price IS DISTINCT FROM p_min_price THEN
            RAISE EXCEPTION
                '배치 키 %는 이미 다른 조건으로 사용되었습니다. 기존 할인율=%, 기존 최소가격=%',
                v_batch_key,
                v_saved_discount,
                v_saved_min_price
                USING ERRCODE = '22023';
        END IF;

        IF v_saved_status = 'COMPLETED' THEN
            p_affected := v_saved_affected;
			--멱등성 요청에서는 재실행 때 0을 반환하기보다 최초 실행 결과와 같은 결과를 반환하는 방식이 일반적입니다.
            RAISE NOTICE
                '배치 %는 이미 완료되었습니다. 할인을 다시 적용하지 않습니다. 기존 처리 건수=%',
                v_batch_key,
                p_affected;

            RETURN;
        END IF;

        RAISE EXCEPTION
            '배치 %가 현재 처리 중입니다.',
            v_batch_key;
    END IF;

    ----------------------------------------------------------------
    -- 4. 최초 요청일 때만 실제 할인 적용
    ----------------------------------------------------------------
    UPDATE proc_lab.products
       SET unit_price = round(
           unit_price
           * (1 - p_discount_percent / 100.0),
           2
       )
     WHERE active
       AND unit_price >= p_min_price;

    GET DIAGNOSTICS p_affected = ROW_COUNT;

    ----------------------------------------------------------------
    -- 5. 배치 실행 완료 기록
    ----------------------------------------------------------------
    UPDATE proc_lab.bulk_discount_runs
       SET affected_count = p_affected,
           run_status     = 'COMPLETED',
           completed_at   = clock_timestamp()
     WHERE batch_key = v_batch_key;

    RAISE NOTICE
        '배치 % 할인 완료: 할인율=%, 최소가격=%, 처리건수=%',
        v_batch_key,
        p_discount_percent::text || '%',
        p_min_price,
        p_affected;
END;
$procedure$;

--멱등성 적용 프로시저 호출
--할인 도중 오류가 발생하면 상품 가격 변경과 배치 실행 기록이 같은 트랜잭션에서 함께 롤백됩니다.
CALL proc_lab.pr_bulk_discount_idempotent(
    'SALE-20260725-001',
    5,
    100000,
    NULL
);
--실행 이력 확인
SELECT
    batch_key,
    discount_percent,
    min_price,
    affected_count,
    run_status,
    started_at,
    completed_at
FROM proc_lab.bulk_discount_runs
ORDER BY started_at DESC;

-- ============================================================================
-- 14. [고급] EXCEPTION + GET STACKED DIAGNOSTICS + 오류 로그
-- ============================================================================
--| 매개변수         | 모드    | 의미           |
--| ------------ | ----- | ------------ |
--| `p_order_id` | `IN`  | 취소할 주문번호     |
--| `p_message`  | `OUT` | 성공·실패 결과 메시지 |

CREATE OR REPLACE PROCEDURE proc_lab.pr_cancel_order(
    IN  p_order_id bigint,
    OUT p_message  text
)
LANGUAGE plpgsql
AS $procedure$
DECLARE
    v_status  proc_lab.orders.order_status%TYPE; --현재 주문 상태
    v_state   text;						--오류 SQLSTATE
    v_message text;						--오류 메시지
    v_detail  text;						--오류 상세정보
    v_context text;						--오류 발생 위치와 호출 문맥

--중첩 블록과 예외 처리
--바깥쪽 BEGIN ... END는 프로시저 본문
BEGIN  
	--안쪽 BEGIN ... END는 별도의 예외 처리 영역입니다.	
    BEGIN  	
		--안쪽 블록에서 예외가 발생하면 안쪽 블록에서 수행했던 변경은 자동으로 취소됩니다.
		--따라서 상품 재고만 복구되고 주문 상태는 변경되지 않는 불완전한 상태를 방지합니다.
		-- 실제 주문 취소 처리영역입니다.


		--주문 조회 및 행 잠금
	--	INTO STRICT : 	
	--		-결과가 반드시 한 건이어야 합니다.
	--		-주문 존재: v_status에 저장
	--		-주문 없음: NO_DATA_FOUND 예외
	--		-여러 건: TOO_MANY_ROWS 예외
        SELECT order_status
          INTO STRICT v_status  --결과가 반드시 한 건이어야 하며,주문번호에 해당하는 현재 상태를 조회하여 v_status에 저장합니다. 예)v_status = PAID
          FROM proc_lab.orders
         WHERE order_id = p_order_id
         FOR UPDATE;  --해당 주문 행을 잠급니다. 예)동시 취소로 재고가 두 번 복구되는 문제를 방지합니다.


		--취소 불가능한 상태 검사
        IF v_status IN ('SHIPPING', 'COMPLETED') THEN
            RAISE EXCEPTION '배송 중(SHIPPING) 또는 주문완료(COMPLETED) 된 주문은 취소할 수 없습니다.'
                USING ERRCODE = 'P0001',   --P0001은 PL/pgSQL에서 일반적으로 사용하는 사용자 정의 예외 코드입니다.
                      DETAIL = format('order_id=%s, status=%s',
                                      p_order_id, v_status);
--			이 예외는 밖으로 바로 전달되지 않고 아래 EXCEPTION 영역에서 처리됩니다.
        END IF;


		--이미 취소된 주문 처리
		--이미 취소된 주문이면 재고 복구와 상태 변경을 실행하지 않고 프로시저를 종료합니다.
		--		첫 번째 호출:
		--		PAID → CANCELLED
		--		재고 2개 복구
		--		
		--		두 번째 호출:
		--		이미 CANCELLED
		--		재고 복구 안 함
		--이 부분이 멱등성을 보장합니다. 같은 취소 요청이 여러 번 전달되어도 최종 상태와 재고가 달라지지 않습니다.
        IF v_status = 'CANCELLED' THEN
            p_message := format('주문 %s는 이미 취소되었습니다.', p_order_id);
            RETURN;  --프로시저를 종료합니다.
        END IF;


		--주문 상품 재고 복구 : 주문 상세에 기록된 수량만큼 상품 재고를 복구합니다.
		--UPDATE ... FROM을 사용해 주문 상품을 한 번에 복구하는 집합 기반 처리입니다.
		--order_items에 다음 고유 제약조건이 있어서 한 상품이 한 행만 존재합니다.
        UPDATE proc_lab.products AS p
           SET stock_qty = p.stock_qty + oi.quantity
          FROM proc_lab.order_items AS oi
         WHERE oi.order_id = p_order_id
           AND oi.product_id = p.product_id;


		--주문 상태 변경
		--주문 상태를 CANCELLED로 변경하고 실제 변경 시각을 기록합니다.
        UPDATE proc_lab.orders
           SET order_status = 'CANCELLED',
               updated_at   = clock_timestamp()  --clock_timestamp()는 실제로 코드가 실행되는 현재 시각을 반환합니다.
         WHERE order_id = p_order_id;


		--상태 변경 이력 저장 : 변경 전후 상태를 이력 테이블에 저장합니다.
        INSERT INTO proc_lab.order_status_history
            (order_id, old_status, new_status)
        VALUES
            (p_order_id, v_status, 'CANCELLED');

		--정상 처리 메시지
        p_message := format('주문 %s 취소 및 재고 복구 완료', p_order_id);

	--안쪽 블록에서 발생한 대부분의 예외를 처리합니다.
    EXCEPTION
        WHEN OTHERS THEN
			-- 오류 처리
			--다음 오류들이 여기에 포함될 수 있습니다.
			--
			--존재하지 않는 주문번호
			--배송 중 또는 완료 주문
			--재고 복구 중 오류
			--주문 상태 변경 오류
			--변경 이력 저장 오류
			--제약조건 위반
			--자료형 오류
            GET STACKED DIAGNOSTICS  --방금 발생한 예외의 상세정보를 변수에 저장합니다.
                v_state   = RETURNED_SQLSTATE,  --오류 코드
                v_message = MESSAGE_TEXT,		--오류 메시지
                v_detail  = PG_EXCEPTION_DETAIL,--추가 오류정보
                v_context = PG_EXCEPTION_CONTEXT;--오류가 발생한 함수·프로시저와 위치
			--GET STACKED DIAGNOSTICS는 반드시 EXCEPTION 처리 영역 안에서 사용해야 합니다.


			--오류 로그 저장 : 오류 정보를 로그 테이블에 저장합니다.
            INSERT INTO proc_lab.routine_error_log
                (routine_name, error_state, error_message,
                 error_detail, error_context)
            VALUES
                ('pr_cancel_order', v_state, v_message,
                 v_detail, v_context);

            -- 오류를 다시 발생시키지 않는 이유:재발생시키지 않으므로 오류 로그가 같은 트랜잭션에서 보존된다.
			-- 호출자는 SQL 오류 대신 메시지를 결과로 받습니다.
            p_message := format('취소 실패 [%s] %s', v_state, v_message);
    END;
END;
$procedure$;


--주문을 취소할 수 있는지 확인하고, 취소 가능하면 주문 상품의 재고를 복구하고 상태 변경 이력을 저장합니다. 
--오류가 발생하면 오류를 다시 던지지 않고 로그 테이블에 기록한 뒤 실패 메시지를 반환합니다.
--또한 이미 취소된 주문은 재고를 다시 더하지 않으므로 멱등성도 적용된 취소 프로시저입니다.
CALL proc_lab.pr_cancel_order(5, NULL); -- 정상 취소 : 예)주문 5 취소 및 재고 복구 완료
CALL proc_lab.pr_cancel_order(2, NULL); -- SHIPPING 이므로 실패하고 로그 기록 : 예)취소 실패 [P0001] 배송 중 또는 완료 주문은 취소할 수 없습니다.

--오류 원인과 발생 위치를  조회할 수 있습니다.
SELECT * FROM routine_error_log ORDER BY log_id;


-- ============================================================================
-- 15. [고급 함수] JSONB 영수증 반환
-- ============================================================================
--이 함수는 주문번호 하나를 받아 주문 정보, 고객 정보, 주문 상품 목록을 
--하나의 중첩된 JSONB 영수증으로 만들어 반환합니다.
CREATE OR REPLACE FUNCTION proc_lab.fn_order_receipt_json(
    p_order_id bigint			--조회할 주문번호
)
RETURNS jsonb					--JSONB 형식으로 결과 반환
LANGUAGE plpgsql				--PL/pgSQL로 작성
stable							--같은 SQL 문 안에서는 안정적인 조회 결과 : 영수증 조회 함수
--이 함수는 테이블 데이터가 변경되면 결과도 달라지므로 IMMUTABLE은 적합하지 않고 STABLE이 적합합니다.
--따라서 NULL 주문번호에 대해 예외를 발생시키고 싶다면 STRICT를 제거하고 함수 본문에서 직접 검사해야 합니다.
strict							--입력값이 NULL이면 함수 본문을 실행하지 않고 NULL 반환
AS $function$
DECLARE
    v_result jsonb;  --결과 저장 변수 : 최종으로 만들어진 JSONB 영수증을 저장하는 지역변수입니다.
BEGIN
	--{K:V,{K:V}} : 이런 구조를 중첩 JSON 객체라고 합니다.
	--jsonb_build_object()는 키와 값을 번갈아 작성해 JSONB 객체를 만듭니다.
    SELECT jsonb_build_object(
        'order_id',      o.order_id,
        'status',        o.order_status,
        'ordered_at',    o.ordered_at,			--날짜와 시간은 JSON에서 문자열 형태로 표현됩니다.
        'customer',      jsonb_build_object(	--고객 정보를 중첩 객체로 생성 : 고객 정보는 최상위에 평평하게 넣지 않고 customer라는 하위 객체로 묶습니다.
                             'customer_id', c.customer_id,
                             'name',        c.customer_name,
                             'email',       c.email
                         ),
        'total_amount',  o.total_amount,		--JSONB에서 숫자는 숫자 형식으로 유지됩니다.
        'items',         coalesce(				--주문 상품 배열 생성
            (
                SELECT jsonb_agg(				--jsonb_agg()로 배열 생성 : 각 주문 상품 객체를 하나의 배열로 합칩니다. 예: [{},{}]
                    jsonb_build_object(			--상품 하나(주문 상세 한 행)를 JSON 객체로 변환
                        'product_id',   p.product_id,
                        'product_name', p.product_name,
                        'quantity',     oi.quantity,
                        'unit_price',   oi.unit_price,	--unit_price를 현재 products.unit_price가 아니라 order_items.unit_price에서 가져오는 점이 중요합니다.상품 가격이 나중에 변경돼도 주문 당시 단가를 영수증에 표시할 수 있습니다.
                        'line_amount',  oi.line_amount
                    )
                    ORDER BY oi.order_item_id		--주문 상세번호 순서로 배열 요소를 정렬합니다.JSONB 객체의 키 순서는 보장되지 않지만 items 배열의 상품 순서는 이 ORDER BY에 의해 유지됩니다.
                )
                FROM proc_lab.order_items AS oi		--주문과 상품 JOIN
                JOIN proc_lab.products AS p			--INNER JOIN이므로 연결된 상품이 없는 주문은 조회되지 않습니다.
                  ON p.product_id = oi.product_id
                WHERE oi.order_id = o.order_id		--상관 서브쿼리 : 내부 쿼리에서 외부 쿼리의 o.order_id를 사용하므로 상관 서브쿼리입니다.
            ),
            '[]'::jsonb		--주문 상품이 없을 때 빈 배열 반환 : items: null 보다 items: [] 가 애플리케이션에서 처리하기 편합니다.
        )
    )
      INTO v_result		--주문번호에 해당하는 행이 없으면 SELECT INTO 결과가 없으므로 v_result는 NULL이 됩니다.
      FROM proc_lab.orders AS o					--주문과 고객 JOIN
      JOIN proc_lab.customers AS c				--INNER JOIN이므로 연결된 고객이 없는 주문은 조회되지 않습니다.
        ON c.customer_id = o.customer_id		--주문의 고객번호를 이용해 고객정보를 가져옵니다.
     WHERE o.order_id = p_order_id;				--주문번호로 주문을 찾고, 

	--주문이 없는 경우 : P0002는 PL/pgSQL의 NO_DATA_FOUND에 해당하는 SQLSTATE입니다.
	--현재 코드에서는 INTO STRICT를 사용하지 않고 직접 검사하기 때문에 사용자에게 이해하기 쉬운 오류 메시지를 제공할 수 있습니다.
    IF v_result IS NULL THEN
        RAISE EXCEPTION '주문번호 %를 찾을 수 없습니다.', p_order_id
            USING ERRCODE = 'P0002';
    END IF;

    RETURN v_result;	--JSONB 반환 : {"items":[...],"status":"PAID","order_id":1,...}
END;
$function$;

SELECT jsonb_pretty(proc_lab.fn_order_receipt_json(1));
--예상결과 : 화면 출력용 함수-jsonb_pretty()는 JSONB 데이터를 사람이 읽기 편하도록 들여쓰기해서 text로 반환합니다.

--주문 상태만 추출
SELECT
    proc_lab.fn_order_receipt_json(1)->>'status'
    AS order_status;
--결과: PAID (예시입니다.)

--고객 이름 추출
SELECT
    proc_lab.fn_order_receipt_json(1)
        ->'customer'
        ->>'name'
    AS customer_name;
--결과: 김민준 (예시입니다.)


--상품 배열 추출
SELECT
    proc_lab.fn_order_receipt_json(1)->'items'
    AS items;


--상품을 행으로 펼치기
SELECT item
FROM jsonb_array_elements(
    proc_lab.fn_order_receipt_json(1)->'items'
) AS item;

--성능을 위한 권장 인덱스 : 다른 기본키 인덱스는 일반적으로 이미 존재합니다.
CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON proc_lab.order_items (order_id, order_item_id);

--참고로 이 함수는 주문 한 건의 영수증을 조회할 때 적합합니다. 
--여러 주문에 대해 반복 호출하면 주문마다 내부 쿼리가 실행되므로, 
--대량 영수증 조회가 필요할 때는 별도의 집합 기반 쿼리를 만드는 것이 더 효율적입니다.


--여러 주문을 한 번에 조회하는 집합 기반 쿼리
--집합 기반으로 구현하려면 주문마다 fn_order_receipt_json()을 반복 호출하지 않고, 
--주문 상세를 order_id별로 한 번에 집계한 다음 주문·고객 테이블과 조인하면 됩니다.
--주문번호 1, 2, 3의 영수증을 한 번에 조회하는 예입니다.
--이 함수는 PL/pgSQL 반복문이 필요 없으므로 LANGUAGE sql로 만들었습니다.
CREATE OR REPLACE FUNCTION proc_lab.fn_order_receipts_json(
    p_order_ids bigint[]
)
RETURNS TABLE (
    receipt_order_id bigint,
    receipt          jsonb
)
LANGUAGE sql
STABLE
STRICT
AS $function$

    WITH target_orders AS MATERIALIZED (	--MATERIALIZED는 조회 대상 주문 집합을 먼저 만들어 재사용하도록 합니다. PostgreSQL 12 이상에서 사용할 수 있습니다.
        SELECT
            o.order_id,
            o.customer_id,
            o.order_status,
            o.ordered_at,
            o.total_amount
        FROM proc_lab.orders AS o
        WHERE o.order_id = ANY (p_order_ids) 	--모든 주문 상품을 주문별로 한 번에 집계 : 반복 실행하지 않고 주문번호별로 상품 배열을 생성합니다.
    ),
    item_json AS (
        SELECT
            oi.order_id,

            jsonb_agg(
                jsonb_build_object(
                    'product_id',   p.product_id,
                    'product_name', p.product_name,
                    'quantity',     oi.quantity,
                    'unit_price',   oi.unit_price,
                    'line_amount',  oi.line_amount
                )
                ORDER BY oi.order_item_id
            ) AS items

        FROM target_orders AS t

        JOIN proc_lab.order_items AS oi
          ON oi.order_id = t.order_id

        JOIN proc_lab.products AS p
          ON p.product_id = oi.product_id

        GROUP BY oi.order_id
    )
    SELECT
        t.order_id AS receipt_order_id,

        jsonb_build_object(
            'order_id',     t.order_id,
            'status',       t.order_status,
            'ordered_at',   t.ordered_at,

            'customer', jsonb_build_object(
                'customer_id', c.customer_id,
                'name',        c.customer_name,
                'email',       c.email
            ),

            'total_amount', t.total_amount,

            'items', coalesce(
                i.items,
                '[]'::jsonb		--상품이 없으면 "items": [] 과 같이 반환합니다.
            )
        ) AS receipt

    FROM target_orders AS t

    JOIN proc_lab.customers AS c
      ON c.customer_id = t.customer_id

    LEFT JOIN item_json AS i		--상품이 없는 주문도 표시 : 상품 목록이 없더라도 주문 자체는 결과에 포함됩니다.
      ON i.order_id = t.order_id

    ORDER BY t.order_id;

$function$;

--여러 주문번호 전달용 집합 기반 쿼리 호출
SELECT *
FROM proc_lab.fn_order_receipts_json(
    ARRAY[1, 2, 3]::bigint[]
);


--보기 좋게 출력하려면:
SELECT
    receipt_order_id,
    jsonb_pretty(receipt) AS receipt
FROM proc_lab.fn_order_receipts_json(
    ARRAY[1, 2, 3]::bigint[]
);

--모든 영수증을 JSON 배열 하나로 반환
--여러 주문의 영수증을 하나의 JSON 배열로 합치려면:
SELECT jsonb_pretty(
    coalesce(
        jsonb_agg(
            r.receipt
            ORDER BY r.receipt_order_id
        ),
        '[]'::jsonb
    )
) AS receipts
FROM proc_lab.fn_order_receipts_json(
    ARRAY[1, 2, 3]::bigint[]
) AS r;

--날짜 범위로 대량 조회
--주문번호 배열 대신 날짜 조건을 사용할 수도 있습니다.
WITH target_orders AS MATERIALIZED (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_status,
        o.ordered_at,
        o.total_amount
    FROM proc_lab.orders AS o
    WHERE o.ordered_at >= DATE '2026-07-01'
      AND o.ordered_at <  DATE '2026-08-01'
)
SELECT *
FROM target_orders
ORDER BY ordered_at;

--날짜 조회가 많다면 다음 인덱스도 유용합니다.
CREATE INDEX IF NOT EXISTS idx_orders_ordered_at
    ON proc_lab.orders (ordered_at);

--주문 상세 집계를 위한 인덱스:
CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON proc_lab.order_items (
        order_id,
        order_item_id
    );


-------------------------------------------------------집합기반쿼리
--반복 함수 호출과 집합 기반 쿼리 차이
------------------------------
--가.반복 함수 호출
--주문 1 → 함수 실행 → 내부 쿼리
--주문 2 → 함수 실행 → 내부 쿼리
--주문 3 → 함수 실행 → 내부 쿼리
--주문이 1,000건이면 함수 내부 쿼리도 주문별로 반복될 수 있습니다.
--
--나.집합 기반 쿼리(PL/pgSQL의 FOR LOOP를 사용하지 않는 것이 핵심입니다.)
--함수를 주문마다 반복 호출하지 않음
--        ↓
--대상 주문을 한 번에 조회
--        ↓
--order_items를 order_id별로 GROUP BY
--        ↓
--jsonb_agg로 주문별 상품 배열 생성
--        ↓
--orders, customers와 한 번에 JOIN
---------------------------------------------------------------

--target_orders CTE에서 2026년 7월 주문만 먼저 선택하고, 
--item_json CTE가 그 주문들의 상품을 order_id별로 JSON 배열로 묶으면 
--2026년 7월 주문 영수증을 한 번에 만들 수 있습니다.
WITH target_orders AS MATERIALIZED (
    ----------------------------------------------------------------
    -- 1. 2026년 7월 주문만 먼저 선택
    ----------------------------------------------------------------
    SELECT
        o.order_id,
        o.customer_id,
        o.order_status,
        o.ordered_at,
        o.total_amount
    FROM proc_lab.orders AS o
    WHERE o.ordered_at >= DATE '2026-07-01'
      AND o.ordered_at <  DATE '2026-08-01'
),
item_json AS (
    ----------------------------------------------------------------
    -- 2. 선택된 주문들의 상품을 주문번호별 JSON 배열로 생성
    ----------------------------------------------------------------
    SELECT
        oi.order_id,
        jsonb_agg(
            jsonb_build_object(
                'product_id',   p.product_id,
                'product_name', p.product_name,
                'quantity',     oi.quantity,
                'unit_price',   oi.unit_price,
                'line_amount',  oi.line_amount
            )
            ORDER BY oi.order_item_id
        ) AS items
    FROM target_orders AS t
    JOIN proc_lab.order_items AS oi
      ON oi.order_id = t.order_id
    JOIN proc_lab.products AS p
      ON p.product_id = oi.product_id
    GROUP BY oi.order_id
),
receipts AS (
    ----------------------------------------------------------------
    -- 3. 주문, 고객, 상품 JSON을 합쳐 영수증 생성
    ----------------------------------------------------------------
    SELECT
        t.order_id,
        t.ordered_at,
        jsonb_build_object(
            'order_id',     t.order_id,
            'status',       t.order_status,
            'ordered_at',   t.ordered_at,
            'customer', jsonb_build_object(
                'customer_id', c.customer_id,
                'name',        c.customer_name,
                'email',       c.email
            ),
            'total_amount', t.total_amount,
            'items', coalesce(
                i.items,
                '[]'::jsonb
            )
        ) AS receipt
    FROM target_orders AS t
    JOIN proc_lab.customers AS c
      ON c.customer_id = t.customer_id
    LEFT JOIN item_json AS i
      ON i.order_id = t.order_id
)
----------------------------------------------------------------
-- 4. 주문마다 한 행씩 출력
----------------------------------------------------------------
--SELECT
--    order_id,
--    ordered_at,
--    jsonb_pretty(receipt) AS receipt
--FROM receipts
--ORDER BY ordered_at, order_id;
----------------------------------------------------------------
-- 5. 모든 영수증을 배열 하나로 반환하려면 바로위 위에 SELECT문 주석 후 아래 주석풀고 실행
----------------------------------------------------------------
SELECT jsonb_pretty(
    coalesce(
        jsonb_agg(
            receipt
            ORDER BY ordered_at, order_id
        ),
        '[]'::jsonb
    )
) AS receipts
FROM receipts;
-----------------------------------------------------7월 주문 영수증 끝------------
--날짜 조회 성능용 인덱스
CREATE INDEX IF NOT EXISTS idx_orders_ordered_at
    ON proc_lab.orders (ordered_at);
--주문 상품 집계용 인덱스
CREATE INDEX IF NOT EXISTS idx_order_items_order_item
    ON proc_lab.order_items (
        order_id,
        order_item_id
    );
--전체 처리 구조는 다음과 같습니다.
	--2026년 7월 주문 전체 조회
	--          ↓
	--해당 주문의 주문 상세 전체 조회
	--          ↓
	--order_id별 상품 JSON 배열 생성
	--          ↓
	--고객정보 JOIN
	--          ↓
	--주문별 영수증 JSONB 생성
	--          ↓
	--주문별 행 또는 전체 JSON 배열로 반환



-- ============================================================================
-- 16. [고급 함수] 안전한 동적 SQL — regclass + format + USING
-- ============================================================================
--이 함수는 동적 SQL의 식별자와 값은 처리 방법이 다르다는 점을 보여주는 예제입니다.
CREATE OR REPLACE FUNCTION proc_lab.fn_count_rows_dynamic(
    p_table  regclass,	--조회 대상 테이블 : 테이블 이름을 단순 text로 받는 것보다 안전합니다.
    p_column name,		--조건을 적용할 컬럼
    p_value  text		--비교할 값
)
RETURNS bigint			--PostgreSQL의 count(*) 반환 타입이 bigint이기 때문입니다.
LANGUAGE plpgsql
stable					--이 함수는 테이블을 조회하지만 데이터를 변경하지 않습니다.그러므로 IMMUTABLE은 적절하지 않습니다
AS $function$
DECLARE
    v_sql   text;
    v_count bigint;
BEGIN
    /*
      식별자(테이블/컬럼)는 바인딩할 수 없으므로 regclass와 %I를 사용한다.
      값은 문자열에 붙이지 말고 반드시 USING으로 전달한다.

      교육용 범용 예제라 컬럼을 text로 변환한다.
      대용량 운영 쿼리에서는 타입별 함수 또는 정적 SQL로 작성해
      인덱스를 활용할 수 있게 하는 편이 좋다.
	  p_table은 이미 PostgreSQL이 확인한 regclass 객체이므로 %s를 사용합니다.
	  %I: SQL (테이블/컬럼)식별자 << %I는 식별자를 안전하게 인용합니다.
	  테이블에는 %I가 아니라 %s를 쓴 이유는 스키마와 테이블을 적절하게 표현하기위해서 입니다.
	  IS NOT DISTINCT FROM : NULL 컬럼까지 세고 싶을때, NULL끼리도 같은 값으로 처리합니다.
	  $1의 의미 : $1은 함수의 첫 번째 매개변수인 p_table을 의미하지 않습니다. 동적 SQL의 $1은 다음 USING 절에서 전달되는 첫 번째 값을 의미합니다.
    */
    v_sql := format(
        'SELECT count(*) FROM %s 
		 WHERE %I::text 
		 IS NOT DISTINCT FROM 		
		 $1',
        p_table,
        p_column
    );

	RAISE NOTICE '동적 SQL: %', v_sql;	--동적 SQL: SELECT count(*) FROM proc_lab.orders WHERE order_status::text = $1
	RAISE NOTICE '바인딩 값: %', p_value;	--바인딩 값: PENDING


	--실제로는 검색값을 SQL 문자열에 직접 넣지 않고 $1 바인딩 변수로 안전하게 전달합니다.
    EXECUTE v_sql		--만들어진 동적 SQL 실행 
	INTO v_count 		--조회 결과를 변수에 저장
	USING p_value;   	--$1 자리에 값을 안전하게 전달 : 값을 문자열 결합하지 않고 $1 + USING으로 바인딩

    RETURN v_count;
END;
$function$;

SELECT pg_typeof(count(*)) FROM proc_lab.orders; --RETURNS bigint 인 이유.

--이 함수는 테이블명·컬럼명·검색값을 매개변수로 받아 동적으로 COUNT(*) 쿼리를 만들고 조건에 맞는 행 개수를 반환합니다.
--regclass 사용시 PostgreSQL은 함수 호출 전에 다음을 확인합니다.
	--해당 테이블이 실제로 존재하는가?
	--현재 사용자가 테이블을 참조할 수 있는가?
	--정확히 어떤 테이블 객체인가?
	--존재하지 않는 테이블이면 함수가 실행되기 전에 오류가 발생합니다.
-- 문자 컬럼
SELECT proc_lab.fn_count_rows_dynamic(
           'proc_lab.orders'::regclass,		--regclass는 테이블 이름을 단순 문자열이 아니라 PostgreSQL의 데이터베이스 객체 식별자로 받는 타입입니다.
           'order_status',
           'PENDING'
       ) AS pending_count;

-- 숫자 컬럼
SELECT proc_lab.fn_count_rows_dynamic(
    'proc_lab.orders'::regclass,
    'customer_id',
    '1'
);

-- 날짜 컬럼
SELECT proc_lab.fn_count_rows_dynamic(
    'proc_lab.orders'::regclass,
    'ordered_at',
    '2026-07-25 10:30:00+09'
);

-- SQL Injection처럼 보이는 값도 USING으로 안전하게 하나의 값으로 처리된다.
SELECT proc_lab.fn_count_rows_dynamic(
           'proc_lab.orders'::regclass,
           'order_status',
           $$PENDING' OR '1'='1$$
       ) AS injection_attempt_count;

--이 함수는 범용 교육 예제나 소량 데이터 조회에 적합합니다.
--대량 운영 데이터에서는 다음과 같은 정적 SQL이 더 좋습니다.
SELECT count(*)
FROM proc_lab.orders
WHERE order_status = 'PENDING';
-- ============================================================================
-- 17. [고급] 트리거 함수 — 주문 변경 자동 감사
-- ============================================================================
--트리거 함수에는 일반 매개변수가 없어도 PostgreSQL이 다음과 같은 특별한 값을 자동으로 제공합니다.
--NEW
--OLD
--TG_OP
--TG_TABLE_NAME
--TG_TABLE_SCHEMA

CREATE OR REPLACE FUNCTION proc_lab.fn_audit_orders()
RETURNS trigger		--일반 함수와 트리거 함수 차이 : 트리거 함수는 일반 함수와 달리 직접 호출하기 위한 함수가 아닙니다.
LANGUAGE plpgsql
SECURITY definer	--함수를 호출한 사용자의 권한이 아니라 함수 소유자의 권한으로 실행한다는 의미입니다.
SET search_path = pg_catalog, proc_lab, pg_temp
AS $function$
--| 스키마          | 역할                       |
--| ------------ | ------------------------ |
--| `pg_catalog` | PostgreSQL 기본 함수와 시스템 객체 |
--| `proc_lab`   | 실습용 테이블과 함수              |
--| `pg_temp`    | 임시 스키마, 가장 뒤에 배치         |

BEGIN
	--실제 값이 변경된 경우에만 기록하고 싶다면 함수의 시작 부분에 다음 조건을 추가합니다.
	IF TG_OP = 'UPDATE'
       AND NEW IS NOT DISTINCT FROM OLD THEN
        RETURN NEW;
    END IF;

    INSERT INTO proc_lab.audit_log		--대상 테이블을 지정하는 것도 좋습니다.
        (table_name, operation, row_id, old_data, new_data)	--감사 로그 입력
			--| 컬럼           | 저장 내용                        |
			--| ------------ | ------------------------------ |
			--| `table_name` | 변경된 테이블명                     |
			--| `operation`  | `INSERT`, `UPDATE`, `DELETE`   |
			--| `row_id`     | 변경된 주문번호                     |
			--| `old_data`   | 변경 전 데이터                     |
			--| `new_data`   | 변경 후 데이터                     |
    VALUES
        (
			--TG_TABLE_SCHEMA	--스키마명도 필요하다면 이 변수를 사용할 수 있습니다.
            TG_TABLE_NAME,		--트리거가 실행된 테이블 이름입니다.현재 트리거는 orders에 연결되어 있습니다.
            TG_OP,				--트리거를 발생시킨 SQL 작업 종류를 나타냅니다.오퍼레이션
            coalesce(			--변경된 주문번호 추출:먼저 NEW에서 order_id를 찾고, 값이 없으면 OLD에서 찾습니다.
                (to_jsonb(NEW) ->> 'order_id')::bigint,
                (to_jsonb(OLD) ->> 'order_id')::bigint
            ),
            CASE WHEN TG_OP IN ('UPDATE', 'DELETE')	--old_data 저장 조건
                 THEN to_jsonb(OLD) END,			--행 전체를 JSONB 객체로 변환합니다.
            CASE WHEN TG_OP IN ('INSERT', 'UPDATE')	--new_data 저장 조건
                 THEN to_jsonb(NEW) END				--행 전체를 JSONB 객체로 변환합니다.
        );
--NEW와 OLD는 변경 전후의 전체 행을 나타냅니다.
--	| 작업       | `OLD`  | `NEW`    |
--	| -------- | ------ | -------- |
--	| `INSERT` | 없음     | 새로 입력된 행 |
--	| `UPDATE` | 변경 전 행 | 변경 후 행   |
--	| `DELETE` | 삭제 전 행 | 없음       |

	
    IF TG_OP = 'DELETE' THEN		--DELETE일 때 RETURN OLD : DELETE: 삭제 전 행인 OLD
        RETURN OLD;
    END IF;

    RETURN NEW;						--INSERT, UPDATE: 변경 후 행인 NEW
--BEFORE 트리거 → RETURN 값이 중요
--AFTER 트리거  → RETURN 값이 무시됨
--따라서 현재 코드에서 RETURN OLD, RETURN NEW는 관례적으로 작성한 형태입니다.
END;
$function$;


--이 코드는 orders 테이블에 INSERT, UPDATE, DELETE가 발생할 때마다 변경 전후 데이터를 
--audit_log 테이블에 자동 저장하는 감사(Audit) 트리거입니다.
--사용자가 별도로 로그를 입력하지 않아도 주문 데이터가 변경되면 트리거가 자동으로 변경 이력을 기록합니다.

DROP TRIGGER IF EXISTS trg_orders_audit
ON proc_lab.orders;						--트리거를 삭제해도 트리거 함수와 기존 감사 로그는 삭제되지 않습니다.

CREATE TRIGGER trg_orders_audit			--트리거 생성
AFTER INSERT OR UPDATE OR delete		--주문 변경이 성공한 다음 트리거 함수를 실행합니다.
ON proc_lab.orders						--스키마를 명시하는 것이 안전합니다.
FOR EACH row							--변경된 행마다 한 번씩 트리거를 실행합니다.주문 100건이 변경되면:감사 로그 100건 생성
EXECUTE FUNCTION proc_lab.fn_audit_orders();

--전체 실행 흐름
--orders에서 INSERT·UPDATE·DELETE 발생
--                ↓
--trg_orders_audit 트리거 자동 실행
--                ↓
--fn_audit_orders() 트리거 함수 호출
--                ↓
--작업 종류와 변경 전후 행을 JSONB로 변환
--                ↓
--audit_log 테이블에 감사 이력 INSERT
--이 감사 로그는 원본 주문 변경과 같은 트랜잭션에 포함됩니다. 원본 작업을 ROLLBACK하면 감사 로그도 함께 롤백됩니다.


UPDATE proc_lab.orders
SET note = '감사 로그 테스트'
WHERE order_id = 1;

SELECT audit_id, table_name, operation, row_id, changed_by, changed_at
FROM proc_lab.audit_log
ORDER BY audit_id;


-- ============================================================================
-- 18. [고급] 함수의 변동성: IMMUTABLE / STABLE / VOLATILE
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_grade_discount_rate(
    p_grade text
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $function$
    SELECT CASE upper(p_grade)
               WHEN 'VIP'    THEN 0.15
               WHEN 'GOLD'   THEN 0.10
               WHEN 'SILVER' THEN 0.05
               ELSE 0
           END;
$function$;

SELECT customer_name,
       customer_grade,
       proc_lab.fn_grade_discount_rate(customer_grade) AS discount_rate
FROM customers
ORDER BY customer_id;

/*
  분류 기준
    IMMUTABLE : 같은 입력이면 언제나 같은 결과. 테이블/현재시간 의존 금지.
    STABLE    : 한 SQL 문 안에서는 결과가 안정적. 조회 함수에 적합.
    VOLATILE  : 호출 때마다 달라질 수 있음. DML, random(), clock_timestamp() 등.

  잘못된 변동성 표시는 옵티마이저에게 거짓 약속을 하는 것이므로
  결과 오류나 잘못된 캐시/인덱스 동작을 만들 수 있다.
*/


-- ============================================================================
-- 19. [고급] SECURITY DEFINER를 안전하게 구성
-- ============================================================================

CREATE OR REPLACE FUNCTION proc_lab.fn_customer_is_active(
    p_customer_id bigint
)
RETURNS boolean
LANGUAGE sql
STABLE
STRICT
SECURITY DEFINER
SET search_path = pg_catalog, proc_lab, pg_temp
AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM proc_lab.customers AS c
        WHERE c.customer_id = p_customer_id
          AND c.active
    );
$function$;

-- 기본 PUBLIC 실행 권한을 제거한 뒤 필요한 역할에만 GRANT하는 패턴
REVOKE ALL
ON FUNCTION fn_customer_is_active(bigint)
FROM PUBLIC;

-- 교육 환경에 실제 역할이 있을 때만 아래 예를 수정하여 실행한다.
-- GRANT EXECUTE ON FUNCTION fn_customer_is_active(bigint) TO app_user;

-- 함수 소유자는 REVOKE PUBLIC 이후에도 실행할 수 있다.
SELECT proc_lab.fn_customer_is_active(1);


-- ============================================================================
-- 20. [고급 프로시저] COMMIT / ROLLBACK 데모 - PPT 없음 스크립트만 확인
-- ============================================================================

CREATE OR REPLACE PROCEDURE proc_lab.pr_transaction_demo(
    IN p_first_message  text,
    IN p_second_message text
)
LANGUAGE plpgsql
AS $procedure$
BEGIN
    INSERT INTO proc_lab.transaction_demo_log(message)
    VALUES (p_first_message);

    COMMIT;  -- 첫 번째 INSERT 확정, 자동으로 새 트랜잭션 시작

    INSERT INTO proc_lab.transaction_demo_log(message)
    VALUES (p_second_message);

    ROLLBACK; -- 두 번째 INSERT 취소, 다시 새 트랜잭션 시작

    INSERT INTO proc_lab.transaction_demo_log(message)
    VALUES ('ROLLBACK 이후 새 트랜잭션에서 입력된 행');
END;
$procedure$;

/*
  다음 CALL은 반드시 "단독 문장"으로 실행한다.

  실행 가능 조건
    1) CALL이 최상위에서 실행되어야 한다.
    2) 명시적 BEGIN ... COMMIT 트랜잭션 블록 안에서 실행하면 안 된다.
    3) 중간에 SELECT 함수 호출이 끼어든 중첩 호출 구조이면 안 된다.
    4) SECURITY DEFINER 또는 CREATE PROCEDURE의 SET 절이 붙은 프로시저는
       트랜잭션 제어문을 실행할 수 없다.
    5) EXCEPTION 처리 블록(내부적으로 서브트랜잭션) 안에서는 종료할 수 없다.

  DBeaver에서는 Auto-commit 상태에서 CALL 한 문장만 선택하여 실행한다.
*/

-- CALL proc_lab.pr_transaction_demo('COMMIT으로 남을 행', 'ROLLBACK으로 사라질 행');
-- SELECT * FROM transaction_demo_log ORDER BY log_id;


-- ============================================================================
-- 21. 루틴 메타데이터 조회와 관리
-- ============================================================================

CREATE OR REPLACE VIEW proc_lab.v_routine_inventory AS
SELECT n.nspname AS routine_schema,
       p.proname AS routine_name,
       CASE p.prokind
           WHEN 'f' THEN 'FUNCTION'
           WHEN 'p' THEN 'PROCEDURE'
           WHEN 'a' THEN 'AGGREGATE'
           WHEN 'w' THEN 'WINDOW'
       END AS routine_kind,
       pg_get_function_identity_arguments(p.oid) AS identity_arguments,
       l.lanname AS language_name,
       CASE p.provolatile
           WHEN 'i' THEN 'IMMUTABLE'
           WHEN 's' THEN 'STABLE'
           WHEN 'v' THEN 'VOLATILE'
       END AS volatility,
       CASE p.proparallel
           WHEN 's' THEN 'SAFE'
           WHEN 'r' THEN 'RESTRICTED'
           WHEN 'u' THEN 'UNSAFE'
       END AS parallel_safety,
       p.prosecdef AS security_definer,
       pg_get_userbyid(p.proowner) AS owner_name
FROM pg_catalog.pg_proc AS p
JOIN pg_catalog.pg_namespace AS n
  ON n.oid = p.pronamespace
JOIN pg_catalog.pg_language AS l
  ON l.oid = p.prolang
WHERE n.nspname = 'proc_lab'
  AND p.prokind IN ('f', 'p');

SELECT *
FROM v_routine_inventory
ORDER BY routine_kind, routine_name, identity_arguments;

-- 함수/프로시저 원문 확인
SELECT proc_lab.pg_get_functiondef('proc_lab.fn_line_total(numeric,integer,numeric)'::regprocedure);

-- psql에서는 다음 메타 명령도 유용하다.
-- \df+ proc_lab.*
-- \sf proc_lab.fn_line_total

-- 시그니처를 지정하여 정확히 삭제하는 방법
-- DROP FUNCTION  IF EXISTS fn_tax_amount(numeric, numeric);
-- DROP PROCEDURE IF EXISTS pr_change_order_status(bigint, text);


-- ============================================================================
-- 22. 성능 점검 — 함수가 인덱스 사용을 가리지 않는지 확인
-- ============================================================================

ANALYZE customers;
ANALYZE products;
ANALYZE orders;
ANALYZE order_items;

EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM fn_orders_by_status('PENDING');

/*
  성능 원칙
    - 가능한 경우 반복문보다 한 번의 집합 기반 SQL을 사용한다.
    - WHERE 컬럼을 함수로 감싸면 인덱스를 못 쓸 수 있으므로 확인한다.
    - 함수 내부 SQL도 EXPLAIN 가능한 형태로 따로 꺼내 검증한다.
    - PL/pgSQL 동적 EXECUTE는 실행 때마다 계획되므로 꼭 필요한 곳에만 쓴다.
    - IMMUTABLE/STABLE/VOLATILE을 실제 동작과 정확히 맞춘다.
*/


-- ============================================================================
-- 23. 자동 검증용 스모크 테스트
-- ============================================================================

DO $test$
DECLARE
    v_result numeric;
    v_count  bigint;
BEGIN
    v_result := fn_line_total(10000, 2, 10);
    IF v_result <> 18000.00 THEN
        RAISE EXCEPTION 'fn_line_total 테스트 실패: %', v_result;
    END IF;

    v_count := fn_count_rows_dynamic(
        'proc_lab.orders'::regclass,
        'order_status',
        'PENDING'
    );
    IF v_count < 0 THEN
        RAISE EXCEPTION '동적 카운트 함수 테스트 실패';
    END IF;

    IF fn_grade_discount_rate('VIP') <> 0.15 THEN
        RAISE EXCEPTION '등급 할인 함수 테스트 실패';
    END IF;

    RAISE NOTICE '스모크 테스트 통과: 주요 함수가 예상대로 동작합니다.';
END;
$test$;


-- ============================================================================
-- 24. 최종 확인
-- ============================================================================

SELECT 'customers' AS table_name, count(*) AS row_count FROM customers
UNION ALL
SELECT 'products', count(*) FROM products
UNION ALL
SELECT 'orders', count(*) FROM orders
UNION ALL
SELECT 'order_items', count(*) FROM order_items
UNION ALL
SELECT 'order_status_history', count(*) FROM order_status_history
UNION ALL
SELECT 'audit_log', count(*) FROM audit_log
UNION ALL
SELECT 'routine_error_log', count(*) FROM routine_error_log
ORDER BY table_name;


