-- ============================================================
-- DDL : 테이블 생성
-- ============================================================
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS majors CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
 
CREATE TABLE "students" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "student_no" varchar(20) UNIQUE NOT NULL,
    "name" varchar(100) NOT NULL,
    "email" varchar(200) UNIQUE NOT NULL,
    "major_id" int,
    "grade" smallint NOT NULL,
    "created_at" timestamp DEFAULT 'now()'
);
 
CREATE TABLE "majors" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" varchar(20) UNIQUE NOT NULL,
    "name" varchar(100) NOT NULL
);
 
CREATE TABLE "courses" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "course_code" varchar(20) UNIQUE NOT NULL,
    "name" varchar(100) NOT NULL,
    "credit" smallint NOT NULL
);
 
CREATE TABLE "enrollments" (
    "student_id" bigint,
    "course_id" int,
    "score" decimal(5,2),
    "enrolled_at" date NOT NULL,
    PRIMARY KEY ("student_id", "course_id")
);
 
-- ============================================================
-- COMMENT : 컬럼 설명
-- ============================================================
COMMENT ON COLUMN "students"."id" IS 'PK';
COMMENT ON COLUMN "students"."student_no" IS '학번';
COMMENT ON COLUMN "students"."major_id" IS 'FK → 학과';
COMMENT ON COLUMN "students"."grade" IS '1~4학년';
 
-- ============================================================
-- ALTER : 외래키 설정
-- ============================================================
ALTER TABLE "students" ADD FOREIGN KEY ("major_id")
    REFERENCES "majors" ("id") DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE "enrollments" ADD FOREIGN KEY ("student_id")
    REFERENCES "students" ("id") DEFERRABLE INITIALLY IMMEDIATE;
 
ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id")
    REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;
 
-- ============================================================
-- INSERT : 테이블별 더미 데이터 입력
-- ============================================================
-- ① 학과 데이터 (majors)
INSERT INTO majors (code, name) VALUES
('CS', '컴퓨터공학과'),
('AI', '인공지능학과'),
('EE', '전자공학과'),
('BA', '경영학과');
 
-- ② 과목 데이터 (courses)
INSERT INTO courses (course_code, name, credit) VALUES
('CS101', 'Java 프로그래밍', 3),
('CS102', 'Python 프로그래밍', 3),
('DB201', '데이터베이스', 3),
('AI301', '머신러닝', 3),
('WEB101', '웹프로그래밍', 3),
('NET201', '컴퓨터네트워크', 3);
 
-- ③ 학생 데이터 (students) - null value 2개설정.
INSERT INTO students
(student_no, name, email, major_id, grade)
VALUES
('2024001','김철수','kim1@test.com',1,1),
('2024002','이영희','lee2@test.com',1,2),
('2024003','박민수','park3@test.com',2,3),
('2024004','최유리','choi4@test.com',2,4),
('2024005','정우성','jung5@test.com',3,2),
('2024006','한지민','han6@test.com',3,1),
('2024007','오세훈','oh7@test.com',4,3),
('2024008','김나영','kim8@test.com',4,4),
('2024009','서지훈','seo9@test.com',null,2),
('2024010','윤아름','yoon10@test.com',null,1);
 
-- ④ 수강 데이터 (enrollments) 학생마다 2과목씩 수강.
INSERT INTO enrollments
(student_id, course_id, score, enrolled_at)
VALUES
(1,1,95.5,'2025-03-02'),(1,3,91.0,'2025-03-02'),
(2,2,88.0,'2025-03-02'),(2,4,92.5,'2025-03-02'),
(3,1,76.0,'2025-03-02'),(3,5,81.5,'2025-03-02'),
(4,3,98.0,'2025-03-02'),(4,4,96.5,'2025-03-02'),
(5,2,79.0,'2025-03-02'),(5,6,85.5,'2025-03-02'),
(6,1,84.5,'2025-03-02'),(6,5,90.0,'2025-03-02'),
(7,4,89.5,'2025-03-02'),(7,6,91.0,'2025-03-02'),
(8,2,94.0,'2025-03-02'),(8,3,87.5,'2025-03-02'),
(9,1,83.0,'2025-03-02'),(9,4,80.0,'2025-03-02'),
(10,5,93.5,'2025-03-02'),(10,6,97.0,'2025-03-02');
 
 
-- # 학사관리 시스템 DQL 종합실습문제
 
-- ## 문제 1. 전체 학생 기본정보 조회
-- 모든 학생의 학번, 학생명, 이메일, 학년을 조회하세요.
-- ### 조회 컬럼
-- * 학번
-- * 학생명
-- * 이메일
-- * 학년구분 - 1(Freshman) → 2(Sophomore) → 3(Junior) → 4(Senior)
 
-- ### 정렬 조건
-- 학번을 기준으로 오름차순 정렬하세요.
 
--### 반드시 사용할 함수
-- CASE WHEN THEN ELSE END
 
-- ### 결과 예시
--| 학번    | 학생명 | 이메일    | 학년구분    |
--| ------- | ----- | ------ | -------------- |
--2024001	김철수	kim1@test.com	Freshman
--2024002	이영희	lee2@test.com	Sophomore
--2024003	박민수	park3@test.com	Junior
--2024004	최유리	choi4@test.com	Senior
--2024005	정우성	jung5@test.com	Sophomore
 
---------------------------------------------------------------------------------------------------------
-- ## 정답 1. 작성영역 -----------------------------------------------------------------------------------
 
SELECT
    student_no AS "학번",
    name       AS "학생명",
    email      AS "이메일",
    CASE grade
        WHEN 1 THEN 'Freshman'
        WHEN 2 THEN 'Sophomore'
        WHEN 3 THEN 'Junior'
        WHEN 4 THEN 'Senior'
    END        AS "학년구분"
FROM students
ORDER BY student_no ASC;
 
---------------------------------------------------------------------------------------------------------
 
-- ## 문제 2. 학생테이블에서 미배정 학과 처리
-- 학생을 조회하되, 학과가 지정되지 않은 학생은 학과명을 `학과 미배정`으로 표시하세요.
 
-- ### 조회 컬럼
-- * 학번
-- * 학생명
-- * 학과명
 
--### 반드시 사용할 함수
--COALESCE()
--CASE WHEN THEN ELSE END
 
-- ### 정렬 조건
-- 학번을 기준으로 오름차순 정렬하세요.
 
-- ### 결과 예시
--| 학번    | 학생명 | 학과명    |
--| ------- | ----- | ------ |
--| 2024001 | 김철수 | 컴퓨터공학과 |
--| 2024002 | 이영희 | 컴퓨터공학과 |
-- 	  ...
--| 2024009 | 서지훈 | 학과 미배정 |
--| 2024010 | 윤아름 | 학과 미배정 |
 
---------------------------------------------------------------------------------------------------------
-- ## 정답 2. 작성영역 -----------------------------------------------------------------------------------
 
SELECT
    s.student_no AS "학번",
    s.name       AS "학생명",
    CASE
        WHEN m.name IS NULL THEN '학과 미배정'
        ELSE COALESCE(m.name, '학과 미배정')
    END          AS "학과명"
FROM students s
LEFT JOIN majors m ON s.major_id = m.id
ORDER BY s.student_no ASC;
 
---------------------------------------------------------------------------------------------------------
 
--## 문제 3. CASE WHEN을 이용한 학점 등급 계산
--
--수강생의 점수를 다음 기준에 따라 등급으로 변환하세요.
--
--|     점수 | 등급  |
--| -----: | --- |
--| 90점 이상 | A   |
--| 80점 이상 | B   |
--| 70점 이상 | C   |
--| 60점 이상 | D   |
--| 60점 미만 | F   |
--|   NULL | 미입력 |
--
--### 조회 컬럼
--
--* 학생명
--* 과목명
--* 점수
--* 등급
--* 수강신청일
--* 수강연도
--* 수강월
--* 학기구분
--* 오늘날짜
--* 경과일수
--
--### 정렬 조건
--등급을 오름차순으로 정렬하세요.
 
--### 주의 사항 2학기 수강신청데이터 더미입력
/*
 
 INSERT INTO enrollments
(student_id, course_id, score, enrolled_at)
VALUES
(1,2,88.0,'2025-09-01'),(1,4,92.5,'2025-09-01'),
(2,1,95.5,'2025-09-01'),(2,3,91.0,'2025-09-01')
ON CONFLICT (student_id, course_id)
DO NOTHING;
 
*/
 
---------------------------------------------------------------------------------------------------------
-- ## 정답 3. 작성영역 -----------------------------------------------------------------------------------
 
-- (주의 사항의 2학기 수강신청 더미 데이터 입력)
INSERT INTO enrollments
(student_id, course_id, score, enrolled_at)
VALUES
(1,2,88.0,'2025-09-01'),(1,4,92.5,'2025-09-01'),
(2,1,95.5,'2025-09-01'),(2,3,91.0,'2025-09-01')
ON CONFLICT (student_id, course_id)
DO NOTHING;
 
SELECT
    s.name                             AS "학생명",
    c.name                             AS "과목명",
    e.score                            AS "점수",
    CASE
        WHEN e.score IS NULL THEN '미입력'
        WHEN e.score >= 90   THEN 'A'
        WHEN e.score >= 80   THEN 'B'
        WHEN e.score >= 70   THEN 'C'
        WHEN e.score >= 60   THEN 'D'
        ELSE 'F'
    END                                AS "등급",
    e.enrolled_at                      AS "수강신청일",
    EXTRACT(YEAR  FROM e.enrolled_at)  AS "수강연도",
    EXTRACT(MONTH FROM e.enrolled_at)  AS "수강월",
    CASE
        WHEN EXTRACT(MONTH FROM e.enrolled_at) BETWEEN 3 AND 8 THEN '1학기'
        ELSE '2학기'
    END                                AS "학기구분",
    CURRENT_DATE                       AS "오늘날짜",
    (CURRENT_DATE - e.enrolled_at)     AS "경과일수"
FROM enrollments e
JOIN students s ON e.student_id = s.id
JOIN courses  c ON e.course_id  = c.id
ORDER BY "등급" ASC;
 
---------------------------------------------------------------------------------------------------------
 