-- =====================================================================
-- PostgreSQL 판매관리 학습용 DDL 및 샘플 데이터
-- 파일명: progresSQL_sales_lab_ddl.sql
-- PostgreSQL 13+ / DBeaver에서 전체 스크립트 실행 가능
-- 주의: 기존 sales_lab 스키마를 삭제하고 다시 생성합니다.
-- =====================================================================

BEGIN;

DROP SCHEMA IF EXISTS sales_lab CASCADE;
CREATE SCHEMA if not exists sales_lab;
SET search_path TO sales_lab, public;

-- 1. 고객
CREATE TABLE customers (
    customer_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name varchar(100) NOT NULL,
    email         varchar(150) NOT NULL UNIQUE,
    phone         varchar(30),
    city          varchar(50) NOT NULL,
    region        varchar(30) NOT NULL,
    customer_grade varchar(10) NOT NULL DEFAULT 'BRONZE',
    signup_date   date NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_customers_grade
        CHECK (customer_grade IN ('BRONZE', 'SILVER', 'GOLD', 'VIP'))
);

-- 2. 상품 카테고리
CREATE TABLE categories (
    category_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(50) NOT NULL UNIQUE
);

-- 3. 상품
CREATE TABLE products (
    product_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id integer NOT NULL,
    product_name varchar(100) NOT NULL UNIQUE,
    list_price   numeric(12,2) NOT NULL,
    stock_qty    integer NOT NULL DEFAULT 0,
    active       boolean NOT NULL DEFAULT true,
    created_at   date NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_products_price CHECK (list_price > 0),
    CONSTRAINT ck_products_stock CHECK (stock_qty >= 0),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

-- 4. 주문
CREATE TABLE orders (
    order_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  integer NOT NULL,
    order_date    date NOT NULL,
    order_status  varchar(15) NOT NULL DEFAULT 'ORDERED',
    payment_method varchar(20) NOT NULL,
    shipping_city varchar(50) NOT NULL,
    CONSTRAINT ck_orders_status
        CHECK (order_status IN ('ORDERED', 'PAID', 'SHIPPED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_orders_payment
        CHECK (payment_method IN ('CARD', 'BANK', 'KAKAO_PAY', 'NAVER_PAY')),
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- 5. 판매 상세
-- 한 주문에 여러 상품이 들어갈 수 있으므로 주문과 상품의 다대다 관계를 해소합니다.
CREATE TABLE sales (
    sale_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      integer NOT NULL,
    product_id    integer NOT NULL,
    quantity      integer NOT NULL,
    unit_price    numeric(12,2) NOT NULL,
    discount_rate numeric(5,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_sales_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_sales_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sales_unit_price CHECK (unit_price > 0),
    CONSTRAINT ck_sales_discount CHECK (discount_rate BETWEEN 0 AND 1),
    CONSTRAINT fk_sales_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

COMMENT ON SCHEMA sales_lab IS 'PostgreSQL 판매관리 종합 실습 스키마';
COMMENT ON TABLE customers IS '고객 기본 정보';
COMMENT ON TABLE categories IS '상품 카테고리';
COMMENT ON TABLE products IS '상품과 현재 재고';
COMMENT ON TABLE orders IS '고객 주문 헤더';
COMMENT ON TABLE sales IS '주문별 상품 판매 상세';
COMMENT ON COLUMN sales.discount_rate IS '0~1 사이 할인율. 예: 0.10은 10%';

-- 외래키 열은 PostgreSQL에서 자동 인덱스가 생성되지 않으므로 직접 생성합니다.
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_order_date ON orders(order_date);
CREATE INDEX idx_sales_order ON sales(order_id);
CREATE INDEX idx_sales_product ON sales(product_id);

-- =====================================================================
-- 샘플 데이터
-- =====================================================================

INSERT INTO customers
    (customer_id, customer_name, email, phone, city, region, customer_grade, signup_date)
VALUES
    (1,  '김민준', 'minjun.kim@example.com', '010-1000-0001', '서울', '수도권', 'VIP',    DATE '2024-01-10'),
    (2,  '이서연', 'seoyeon.lee@example.com','010-1000-0002', '서울', '수도권', 'GOLD',   DATE '2024-02-15'),
    (3,  '박지훈', 'jihoon.park@example.com','010-1000-0003', '인천', '수도권', 'SILVER', DATE '2024-03-20'),
    (4,  '최유나', 'yuna.choi@example.com',  '010-1000-0004', '수원', '수도권', 'GOLD',   DATE '2024-05-08'),
    (5,  '정현우', 'hyunwoo.jung@example.com','010-1000-0005','대전', '충청권', 'SILVER', DATE '2024-06-17'),
    (6,  '강수빈', 'subin.kang@example.com', '010-1000-0006', '청주', '충청권', 'BRONZE', DATE '2024-08-02'),
    (7,  '조도윤', 'doyun.jo@example.com',   '010-1000-0007', '부산', '영남권', 'VIP',    DATE '2024-09-11'),
    (8,  '윤지아', 'jia.yoon@example.com',   '010-1000-0008', '대구', '영남권', 'GOLD',   DATE '2024-11-23'),
    (9,  '장예준', 'yejun.jang@example.com', '010-1000-0009', '광주', '호남권', 'SILVER', DATE '2025-01-05'),
    (10, '임하은', 'haeun.lim@example.com',  '010-1000-0010', '전주', '호남권', 'BRONZE', DATE '2025-02-14'),
    (11, '한시우', 'siwoo.han@example.com',  '010-1000-0011', '제주', '제주권', 'BRONZE', DATE '2025-04-01'),
    (12, '오나연', 'nayeon.oh@example.com',  NULL,            '서울', '수도권', 'BRONZE', DATE '2025-05-19');

INSERT INTO categories (category_id, category_name) VALUES
    (1, '노트북'),
    (2, '모니터'),
    (3, '주변기기'),
    (4, '모바일'),
    (5, '생활가전');

INSERT INTO products
    (product_id, category_id, product_name, list_price, stock_qty, active, created_at)
VALUES
    (1,  1, '울트라북 14',        1450000, 12, true,  DATE '2024-01-05'),
    (2,  1, '게이밍 노트북 16',   2290000,  7, true,  DATE '2024-01-05'),
    (3,  1, '비즈니스 노트북 15', 1780000,  5, true,  DATE '2024-03-01'),
    (4,  2, '27인치 QHD 모니터',    390000, 20, true,  DATE '2024-01-05'),
    (5,  2, '32인치 4K 모니터',     690000, 10, true,  DATE '2024-02-01'),
    (6,  2, '휴대용 모니터',        310000, 15, true,  DATE '2024-06-10'),
    (7,  3, '무선 기계식 키보드',   159000, 30, true,  DATE '2024-01-05'),
    (8,  3, '인체공학 마우스',        89000, 45, true,  DATE '2024-01-05'),
    (9,  3, 'USB-C 도킹스테이션',    219000, 18, true,  DATE '2024-04-15'),
    (10, 3, '노이즈캔슬링 헤드셋',   279000, 22, true,  DATE '2024-07-07'),
    (11, 4, '스마트폰 Pro',         1390000, 14, true,  DATE '2024-09-01'),
    (12, 4, '스마트워치',            420000, 25, true,  DATE '2024-09-01'),
    (13, 4, '태블릿 11',             890000, 11, true,  DATE '2025-01-10'),
    (14, 5, '로봇청소기',            790000,  9, true,  DATE '2025-02-01'),
    (15, 5, '스마트 공기청정기',      540000,  8, false, DATE '2025-02-01');

INSERT INTO orders
    (order_id, customer_id, order_date, order_status, payment_method, shipping_city)
VALUES
    (1,  1,  DATE '2025-01-08', 'COMPLETED', 'CARD',      '서울'),
    (2,  2,  DATE '2025-01-12', 'COMPLETED', 'KAKAO_PAY', '서울'),
    (3,  3,  DATE '2025-01-20', 'COMPLETED', 'CARD',      '인천'),
    (4,  1,  DATE '2025-02-03', 'COMPLETED', 'BANK',      '서울'),
    (5,  4,  DATE '2025-02-14', 'CANCELLED', 'CARD',      '수원'),
    (6,  5,  DATE '2025-02-27', 'COMPLETED', 'NAVER_PAY', '대전'),
    (7,  7,  DATE '2025-03-05', 'COMPLETED', 'CARD',      '부산'),
    (8,  8,  DATE '2025-03-18', 'SHIPPED',   'KAKAO_PAY', '대구'),
    (9,  2,  DATE '2025-04-02', 'COMPLETED', 'CARD',      '서울'),
    (10, 9,  DATE '2025-04-16', 'COMPLETED', 'BANK',      '광주'),
    (11, 3,  DATE '2025-05-07', 'COMPLETED', 'CARD',      '인천'),
    (12, 7,  DATE '2025-05-21', 'COMPLETED', 'NAVER_PAY', '부산'),
    (13, 10, DATE '2025-06-04', 'PAID',      'KAKAO_PAY', '전주'),
    (14, 1,  DATE '2025-06-17', 'COMPLETED', 'CARD',      '서울'),
    (15, 5,  DATE '2025-07-01', 'SHIPPED',   'BANK',      '대전'),
    (16, 8,  DATE '2025-07-11', 'ORDERED',   'CARD',      '대구'),
    (17, 4,  DATE '2025-07-20', 'COMPLETED', 'NAVER_PAY', '수원'),
    (18, 11, DATE '2025-07-25', 'CANCELLED', 'CARD',      '제주');

-- 판매금액 공식: quantity * unit_price * (1 - discount_rate)
-- 취소 주문(5, 18)은 판매 상세를 넣지 않아 OUTER JOIN 연습이 가능하게 합니다.
-- 상품 15는 판매하지 않아 미판매 상품 조회가 가능하게 합니다.
INSERT INTO sales
    (sale_id, order_id, product_id, quantity, unit_price, discount_rate)
VALUES
    (1,  1,  1,  1, 1450000, 0.05),
    (2,  1,  7,  1,  159000, 0.00),
    (3,  1,  8,  1,   89000, 0.00),
    (4,  2,  4,  2,  390000, 0.10),
    (5,  2,  9,  1,  219000, 0.05),
    (6,  3,  2,  1, 2290000, 0.07),
    (7,  3, 10,  1,  279000, 0.00),
    (8,  4, 11,  1, 1390000, 0.05),
    (9,  4, 12,  1,  420000, 0.00),
    (10, 6,  3,  1, 1780000, 0.10),
    (11, 6,  6,  1,  310000, 0.00),
    (12, 7,  5,  2,  690000, 0.12),
    (13, 7,  9,  2,  219000, 0.05),
    (14, 8,  7,  2,  159000, 0.00),
    (15, 8,  8,  2,   89000, 0.00),
    (16, 9, 13,  1,  890000, 0.08),
    (17, 9, 10,  1,  279000, 0.00),
    (18, 10, 4,  1,  390000, 0.00),
    (19, 10, 7,  1,  159000, 0.00),
    (20, 11, 6,  1,  310000, 0.03),
    (21, 11, 9,  1,  219000, 0.00),
    (22, 11, 8,  1,   89000, 0.00),
    (23, 12, 2,  1, 2290000, 0.15),
    (24, 12, 5,  1,  690000, 0.10),
    (25, 13, 14, 1,  790000, 0.05),
    (26, 13, 12, 1,  420000, 0.00),
    (27, 14, 1,  1, 1450000, 0.12),
    (28, 14, 4,  1,  390000, 0.05),
    (29, 14, 7,  1,  159000, 0.00),
    (30, 15, 11, 1, 1390000, 0.10),
    (31, 15, 10, 2,  279000, 0.05),
    (32, 16, 13, 1,  890000, 0.00),
    (33, 17, 14, 1,  790000, 0.08),
    (34, 17, 8,  2,   89000, 0.00),
    (35, 17, 12, 1,  420000, 0.05);

-- 명시적으로 넣은 ID 다음부터 IDENTITY가 충돌하지 않게 현재 최댓값에 맞춥니다.
SELECT setval(pg_get_serial_sequence('customers', 'customer_id'),
              (SELECT MAX(customer_id) FROM customers));
SELECT setval(pg_get_serial_sequence('categories', 'category_id'),
              (SELECT MAX(category_id) FROM categories));
SELECT setval(pg_get_serial_sequence('products', 'product_id'),
              (SELECT MAX(product_id) FROM products));
SELECT setval(pg_get_serial_sequence('orders', 'order_id'),
              (SELECT MAX(order_id) FROM orders));
SELECT setval(pg_get_serial_sequence('sales', 'sale_id'),
              (SELECT MAX(sale_id) FROM sales));

COMMIT;

-- 설치 확인
SET search_path TO sales_lab, public;

SELECT 'customers' AS table_name, COUNT(*) AS row_count FROM customers
UNION ALL SELECT 'categories', COUNT(*) FROM categories
UNION ALL SELECT 'products',   COUNT(*) FROM products
UNION ALL SELECT 'orders',     COUNT(*) FROM orders
UNION ALL SELECT 'sales',      COUNT(*) FROM sales
ORDER BY table_name;

-- 주문별 금액 확인
SELECT
    o.order_id,
    c.customer_name,
    o.order_date,
    o.order_status,
    COALESCE(ROUND(SUM(s.quantity * s.unit_price * (1 - s.discount_rate)), 2), 0)
        AS order_amount
FROM orders o
JOIN customers c ON c.customer_id = o.customer_id
LEFT JOIN sales s ON s.order_id = o.order_id
GROUP BY o.order_id, c.customer_name, o.order_date, o.order_status
ORDER BY o.order_id;

